### ISSUE TITLE
Headers should not include <iostream>

### ISSUE THREAD

**Issue by PeterSommerlad** [hanickadot/compile-time-regular-expressions#1]
Including iostream introduces dependecies to the global stream objects, that when used remove unit-testability from code. If i/o functions are implemented include <istream> and <ostream> instead, or only <iosfwd> when only declarations of such functions are made.

**Comment by hanickadot** [comment]
Fixed in commit d1a7ca40bd48e815603b58e3973d963c59663fc9.
