### ISSUE TITLE
MSVC: compile errors

### ISSUE THREAD

**Issue by matbech** [hanickadot/compile-time-regular-expressions#101]
I get the following compiler errors with Visual Studio 16.7.0 Previous 1 (using /std:c++latest) since the latest commit:

6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\return_type.hpp(43,73): warning C4346: 'ctre::get_name_tag_t<Name>::type': dependent name is not a type (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\return_type.hpp(43,73): message : prefix with 'typename' to indicate a type (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\return_type.hpp(43,73): error C2061: syntax error: identifier 'type' (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\return_type.hpp(48,36): error C2631: 'id_tag': a class or enum cannot be defined in an alias template (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\return_type.hpp(367,15): error C2143: syntax error: missing ';' before '{' (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\return_type.hpp(367,15): error C2447: '{': missing function header (old-style formal list?) (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(10,24): error C2631: 'can_be_anything': a class or enum cannot be defined in an alias template (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\evaluation.hpp(19,1): error C2059: syntax error: '<end Parse>' (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\evaluation.hpp(19,16): error C2143: syntax error: missing ';' before '{' (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\evaluation.hpp(19,16): error C2447: '{': missing function header (old-style formal list?) (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\wrapper.hpp(11,44): error C2631: 'zero_terminated_string_end_iterator': a class or enum cannot be defined in an alias template (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\literals.hpp(12,1): error C2059: syntax error: '<end Parse>' (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\literals.hpp(12,16): error C2143: syntax error: missing ';' before '{' (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\literals.hpp(12,16): error C2447: '{': missing function header (old-style formal list?) (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\functions.hpp(40,42): error C2039: 'pcre': is not a member of 'ctre::ctre::ctre::ctre' (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\functions.hpp(10): message : see declaration of 'ctre::ctre::ctre::ctre' (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\functions.hpp(40,62): error C2039: 'pcre_actions': is not a member of 'ctre::ctre::ctre::ctre' (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\functions.hpp(10): message : see declaration of 'ctre::ctre::ctre::ctre' (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\functions.hpp(43,15): error C2039: 'regular_expression': is not a member of 'ctre::ctre::ctre::ctre' (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\functions.hpp(10): message : see declaration of 'ctre::ctre::ctre::ctre' (compiling source file Parser\GXSEnterpriseParser.cpp)
6>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\functions.hpp(49,45): error C2631: 'regex_match_t': a class or enum cannot be defined in an alias template (compiling source file Parser\GXSEnterpriseParser.cpp)

**Comment by hanickadot** [comment]
Thank you for reporting the error. My mistake, I didn’t try it on MSVC. Will try to fix today CEST evening.

**Comment by hanickadot** [comment]
"Fixed" in 72ea41938bca052fa33d61469213beb76245c788 by rollbacking the change, I was able to fix it, but then I triggered ICE. Will work on it in a branch and merge later.
