### ISSUE TITLE
Probably not an issue, but try to port as much as possible to C++11.

### ISSUE THREAD

**Issue by hanickadot** [hanickadot/compile-time-regular-expressions#12]

**Comment by BenHanson** [comment]
As you've raised this issue, I'd like to add that it would be nice if the code would build under Visual C++.

**Comment by hanickadot** [comment]
It should be possible in MSVC which will be released in Q1 2019. Currently only GCC / Clang supports N3599 extension (templated string literals) which allows to emulate P0732 C++20 (class NonTypeTemplateParameters, NTTP) in current C++. It's impossible to make it work in MSVC until the NTTP supports land.

**Comment by BenHanson** [comment]
Thanks for the info. I'm glad to hear the required support is coming to VC++.

**Comment by hanickadot** [comment]
I found a way how to use library (with a workaround) in MSVC :) #14
