### ISSUE TITLE
Non-greedy matches

### ISSUE THREAD

**Issue by Omnifarious** [hanickadot/compile-time-regular-expressions#125]
This code:

```
#include <ctre.hpp>
#include <utility>

::std::pair<unsigned long long, unsigned long long> test_greedy() {
    static constexpr char mstr[] = "I bought an apple and Thelma bought an apple";
    auto m1 = ctre::match<"^.*apple">(mstr);
    auto m2 = ctre::match<"^.*?apple">(mstr);
    return {m1.get<0>().end() - mstr, m2.get<0>().end() - mstr};
}
```

should return a pair with 44 and 17. Instead it returns a pair with 44 and 44.

Example: https://gcc.godbolt.org/z/cdvvEE

Documentation for non-greedy qualifiers: https://perldoc.perl.org/perlre#Quantifiers

**Comment by hanickadot** [comment]
For this behaviour, you need to use `search` function which is not bounded, `match` function implicitly is same as `search<"^pattern$">`

https://gcc.godbolt.org/z/YaKqqd

**Comment by Omnifarious** [comment]
Oh! *sigh* Thank you!
