### ISSUE TITLE
Bracket expression with leading or trailing hyphen-minus, '[-xyz]' fails to compile. 

### ISSUE THREAD

**Issue by henrik-jensen** [hanickadot/compile-time-regular-expressions#13]
In [POSIX regex](https://en.wikipedia.org/w/index.php?title=Regular_expression&oldid=862646591#POSIX_basic_and_extended) when the hyphen-minus, '-', is first or last in a bracket expression it is translated as a literal and not a range separator. This fails on CTRE though a workaround is to use hex "\\x2D" instead of "-"

Example:
```cpp
#include <string_view>
#include "ctre.hpp"

using namespace std::string_view_literals;
using namespace ctre::literals;
static_assert("^[\\x2D /]+?$"_ctre.match("/- "sv)); // Workaround using hex
static_assert("^[ /\\x2D]+?$"_ctre.match("/- "sv)); // Workaround using hex
static_assert("^[- /]+?$"_ctre.match("/- "sv)); // Compilation failure
static_assert("^[ /-]+?$"_ctre.match("/- "sv)); // Compilation failure
```
View on [Compiler Explorer](https://godbolt.org/z/aMoo_8) using gcc8.2/clang7.0.0 with CTRE trunk (v2 gives the same error).

**Comment by hanickadot** [comment]
Thank you. I will fix it soon :)

**Comment by hanickadot** [comment]
Or you can backslash it `"^[\\-]+?$"_ctre.match("---");`. I will look how the PCRE handle this case and will do the same.

**Comment by henrik-jensen** [comment]
Super.

Btw., neither backslash nor double backslash seems to work and according to the wikipedia article backslash is not allowed in POSIX regex bracket expression to escape characters.

**Comment by hanickadot** [comment]
The escape should work now ... Travis is red, but that's a different issue (with conan and unicode).
