### ISSUE TITLE
MSVC: error C3861: '__PRETTY_FUNCTION__': identifier not found 

### ISSUE THREAD

**Issue by matbech** [hanickadot/compile-time-regular-expressions#133]
ctre\evaluation.hpp(215,31): error C3861: '__PRETTY_FUNCTION__': identifier not found 

I believe __PRETTY_FUNCTION__ is not defined with MSVC

**Comment by Alcaro** [comment]
That is correct. It's a GCC extension; the MSVC equivalent is \_\_FUNCSIG\_\_.

**Comment by hanickadot** [comment]
Sorry 🤷🏻‍♀️ I forgot a debug function 👻 ... It's fixed in 8d876b6c237aa3c5723ef6fbeb624c79b3b9bc9b

**Comment by hanickadot** [comment]
Also I released additional minor release v3.3.2
