### ISSUE TITLE
Support for more anchors (boundaries)

### ISSUE THREAD

**Issue by mbunkus** [hanickadot/compile-time-regular-expressions#134]
Like I wrote on Twitter your work on CTRE motivated me to migrate away from `std::regex` to something else. Unfortunately I regularly (no pun intended) use anchors other than `^` and `$`, and due to lack of support for them in CTRE I settled on PCRE. I'd like to be able to switch to CTRE. Therefore I'm asking for support for more anchors.

Now what "commonly used anchors" are is definitely debatable, so I'm only talking about the ones that I use often enough:

* `\b` for matching word boundaries (and its inverse, `\B`)
* having `^` and `$` do what they do in Perl/PCRE: match the start/end of a line, not of a string (`^` = at the start of the string or directly after a newline and `$` = at the end of the string or directly before a newline). There's an issue for this already: #41 
* as a consequence of the change to `^` and `$`:  `\A` and `\Z` for matching at the start and end of the string

Other anchors such as `\z` or the Unicode-property anchors that Perl supports aren't something I ever use. Again, this is subjective; only talking about my own needs here.

Thanks for considering!

**Comment by hanickadot** [comment]
Thank you! Multiline mode is coming soon. Thank you for letting me know.

**Comment by hanickadot** [comment]
So today I implemented parsing for `\A`,`\Z`,`\z`. The internal API is almost ready to support multiline queries. And I also implemented boundaries, for now only word, but unicode boundaries will be there too (in time).

https://compiler-explorer.com/z/95nM4f

Branch `multiline` if you want to try it.

**Comment by hanickadot** [comment]
Ok multiline mode added in c82b129a4daee23ccec75acf6dd926b739590508, will release as soon I will have tests. You enable the multiline mode with these functions:
```
ctre::multiline_match<"regex">(subject);
ctre::multiline_search<"regex">(subject);
ctre::multiline_starts_with<"regex">(subject);
ctre::multiline_range<"regex">(subject); // this gives you iterable range where each iteration will trigger `search`
ctre::multiline_tokenize<"regex">(subject);  // this gives you iterable range where each iteration will trigger `starts_with`
```

**Comment by hanickadot** [comment]
Merged into `main` branch. I will release new version when I finish the recent problem with cycles.
