### ISSUE TITLE
clang compile fails using ctre inside a template class/function

### ISSUE THREAD

**Issue by faceprint** [hanickadot/compile-time-regular-expressions#138]
```
#include <ctre.hpp>

template <typename T>
bool match(std::string_view line) {
    static constexpr auto pattern = ctll::fixed_string("aloha|[a-z]*");
    return ctre::match<pattern>(line);
}

bool call_match(std::string_view line) {
    return match<int>(line);
}
```

https://compiler-explorer.com/z/aE7YPq

**Comment by faceprint** [comment]
This may be a bug on the clang/llvm side instead.  I'm waiting on getting an account created in their bugtracker, figured I'd post here as well in the meantime.  Feel free to close if there's no good fix/workaround in ctre code.

**Comment by hanickadot** [comment]
Seems you are right, it looks like clang's bug. But for you, you can move the pattern out of the templated function to make it work.

**Comment by faceprint** [comment]
For anyone else tracking this, the clang/llvm bug I filed is here: https://bugs.llvm.org/show_bug.cgi?id=48134
