### ISSUE TITLE
Support for MSVC

### ISSUE THREAD

**Issue by hanickadot** [hanickadot/compile-time-regular-expressions#14]
Waiting for C++20 class NTTP (P0732) support. Check needed.

**Comment by hanickadot** [comment]
This should work now:
```
static constexpr inline auto pattern = ctll::basic_fixed_string{“hello”};

bool match(std::string_view subject) { 
     return ctre::re<pattern>().match(subject);
}
```
(in MSVC 15.8)

**Comment by hanickadot** [comment]
(I don't have MSVC and I'm fixing it at http://godbolt.ms)

**Comment by hanickadot** [comment]
Some work done in msvc branch. Blocked by MSVC ICE for same REs.

**Comment by WimLeflere** [comment]
Maybe you can contact the MSVC team?
They did a lot of work for becoming compatible with Boost.Hana.
https://blogs.msdn.microsoft.com/vcblog/2018/08/30/use-the-official-boost-hana-with-msvc-2017-update-8-compiler/

**Comment by hanickadot** [comment]
I did already. https://developercommunity.visualstudio.com/content/problem/367513/internal-compiler-error-when-porting-ctre-library.html

**Comment by hanickadot** [comment]
it's working!

**Comment by matbech** [comment]
I ran into another compiler error with MSVC 15.8.8. I have reported it here:
https://developercommunity.visualstudio.com/content/problem/370094/fatal-error-c1001-an-internal-error-has-occurred-i-27.html

**Comment by hanickadot** [comment]
You need to have the pattern as an object with static linkage, outside the function:
```
#include "ctre.hpp"

static constexpr auto pattern = ctll::basic_fixed_string{ "(\\w+) (\\w+)!" };

void NotCompilerError()
{
std::wstring hello;
ctre::re<pattern>().match(hello);
}
```

Anyway I think MSFT people will be glad for another ICE.

**Comment by matbech** [comment]
Thank you. It compiles without any errors this way.
