### ISSUE TITLE
Interleaved captures could be made linear*

### ISSUE THREAD

**Issue by Andersama** [hanickadot/compile-time-regular-expressions#160]
Consider a pattern like:
```c
select<
sequence<capture<0, A..., B..., C...>, D...>
sequence<A...,capture<1, B..., C..., D...>
>
```
We can see that when evaluated we may process some portion into the first path only to backtrack and redo all that same work.
However we can emulate a linear sequence fairly easily by combining these two sequences and the instructions to mark the start and end iterators.
EG:
```c
sequence<start_capture<0>,A...,start_capture<1>, B..., C..., end_capture<0>, D..., end_capture<1>>
```
Currently it could be written like:
```c
sequence<capture<0,A...,capture<1,B..., C...>>, D..., numeric_mark<1>>
```

**Comment by hanickadot** [comment]
No, they can't be interleaved, that would mean we loose PCRE compatibility in evaluation of captures by their priorities. This is something for DFA based engines.

**Comment by Andersama** [comment]
Sorry, I messed up the example forgot a comma*
Essentially it's this
```c
sequence<A...,B...,C...,D...>
```
but twice with different placements for the captures.

I think technically here (since I've butchered things) the second branch never really evaluates?
```c
select<
sequence<capture<0, A..., B..., C...>, D...>,
sequence<A...,capture<1, B..., C..., D...>
>
```
Maybe you picked up on what I meant. I don't know what the pcre standard would allow here.

**Comment by hanickadot** [comment]
PCRE always chooses first passing path, so the second capture won't be triggered, unless somewhere later is a back-reference, which can trigger backtracking and choosing second path.
