### ISSUE TITLE
Warning C4702: unreachable code

### ISSUE THREAD

**Issue by Malacath-92** [hanickadot/compile-time-regular-expressions#161]
Using:
- ctre/3.3.4
- MSVC/16.7.1

Pretty much any regex using a _quantifier_ (e.g. `.{2}`) results in a handful of `unreachable code` warnings. Matching with that regex works as expected however. When working with `/Wx` this is still problematic.

The warning comes from right here `ctre\evaluation.hpp(343): warning C4702: unreachable code` while the subsequent warnings are of the same root cause.

```c++
#ifndef CTRE_DISABLE_GREEDY_OPT
	if constexpr (!collides(calculate_first(Content{}...), calculate_first(Tail{}...))) {
		return evaluate(begin, current, end, f, captures, ctll::list<possessive_repeat<A,B,Content...>, Tail...>());
	}
#endif
```
I believe right here is the problem, that `if constexpr` has no else clause.

**Comment by Andersama** [comment]
You could safely ignore that warning, or expand out the constexpr if inside the pragma to get rid of the warning. I did the same on my local copy.
EG:
```c
// (greedy) repeat 
template <typename R, typename Iterator, typename EndIterator, size_t A, size_t B, typename... Content, typename... Tail> 
constexpr CTRE_FORCE_INLINE R evaluate(const Iterator begin, Iterator current, const EndIterator end, [[maybe_unused]] const flags & f, R captures, [[maybe_unused]] ctll::list<repeat<A,B,Content...>, Tail...> stack) {

	if constexpr ((B != 0) && (A > B)) {
		return not_matched;
	}

#ifndef CTRE_DISABLE_GREEDY_OPT
	if constexpr (!collides(calculate_first(Content{}...), calculate_first(Tail{}...))) {
		return evaluate(begin, current, end, f, captures, ctll::list<possessive_repeat<A,B,Content...>, Tail...>());
	} else {
#endif
	
	// A..B
	size_t i{0};
	while (less_than<A>(i)) {
		auto inner_result = evaluate(begin, current, end, not_empty_match(f), captures, ctll::list<Content..., end_cycle_mark>());
		
		if (!inner_result) return not_matched;
		
		captures = inner_result.unmatch();
		current = inner_result.get_end_position();
		
		++i;
	}
	
#ifdef CTRE_MSVC_GREEDY_WORKAROUND
	R result;
	evaluate_recursive(result, i, begin, current, end, f, captures, stack);
	return result;
#else
	return evaluate_recursive(i, begin, current, end, f, captures, stack);
#endif

#ifndef CTRE_DISABLE_GREEDY_OPT
	}
#endif
}
```

**Comment by Malacath-92** [comment]
Yes ofc the warning is fine to ignore, but it's not really a good choice to have every user manually disable the warning, disable warnings as errors or fix the code (which some can't even do easily, for example I use the ctre conan package)

**Comment by hanickadot** [comment]
I would argue, this is bad warning and should be reported to MSVC dev team. The warning is similar as a recent bug in GCC where it warmed about evaluating dependant expression to always false. 

This code is exactly what it is, it's an optimisation / short-path in case when backtracking can be omitted.  Adding else will hurt readability of the code. But I'm going to touch this part of the code, and the evaluation of loops will be different, so there is a chance this won't be triggered anymore.

**Comment by Andersama** [comment]
@Malacath-92 are you allowed to update MSVC? It's not a warning in the latest version which is what I'm working with.

**Comment by Malacath-92** [comment]
Yes, updating MSVC should be fine for me. I will give that a try, thank you  :)

**Comment by Andersama** [comment]
No worries, I know the frustration of warnings / errors, the number of times I've made edits to my pr's because MSVC allows something which gcc or clang doesn't is frustrating and I've probably spammed hana a few times because of it. I will say I'm using MSVC's native cmake support, and to be honest I'm not sure how much of cmake it respects, I don't usually add flags beyond optimization level and c++ standard. I guess another approach would be (I don't know conan packages) would be to make a conan package with the edit you need.
