### ISSUE TITLE
[question] Group repetition output feature?

### ISSUE THREAD

**Issue by yurivict** [hanickadot/compile-time-regular-expressions#164]
Does ```ctre``` support group repetition output? I couldn't find such examples or mentions of this in README.

I needed to get values of each cycle of group repetition in one of my projects, but ```std::regex``` doesn't support this, and I couldn't find this in ```ctre```.

One can imagine a nice ```std::function```-based interface to parse a ```function with arguments``` pattern like this:
```
if (auto m = ctre::match<"([a-z]+)\\(([0-9]+)(,([0-9]+)*)\\)">(str, {[](){/*handle group1*/}, [](){/*handle group2*/}, [](){/*handle group3*/}, [](){/*handle group4*/}})) {
}
```

**Comment by hanickadot** [comment]
I have seen such feature only in .NET regex engine. It would need allocation, which CTRE is not doing it anywhere. Reason for not doing it will callbacks is that the engine can backtrack and suddenly previous capture group which wasn't correct shouldn't be visible to the user.

For you example I recommend do something like:

```
#include <ctre.hpp>
#include <iostream>
#include <optional>

struct function {
	// be aware these can be dangling
	std::string_view name;
	std::string_view arguments;
	
	auto begin() {
		// it's like repeatedly called `ctre::search<"...">()`
		// it will skip anything else, in this case only `,`
		return ctre::iterator<"[0-9]+">(arguments);
	}
	auto end() {
		return ctre::sentinel;
	}
};

std::optional<function> match(std::string_view input) {
	if (auto m = ctre::match<"([a-z]+)\\(([0-9]+(,[0-9]+)*\\))">(input)) {
		return function{m.get<1>().view(), m.get<2>().view()};
	} else {
		return std::nullopt;
	}
}

int main() {
	if (auto opt_fnc = match("hello(1,23,45)")) {
		std::cout << "name: " << opt_fnc->name << "\n";
		for (auto && arg: *opt_fnc) {
			std::cout << "arg: " << arg.view() << "\n";
		}
	}
}
```

**Comment by yurivict** [comment]
Thank you.
