### ISSUE TITLE
CTRE does not accept `.{1}?`

### ISSUE THREAD

**Issue by danlark1** [hanickadot/compile-time-regular-expressions#177]
```cpp
static_assert(".{1}?"_ctre.search("Y"));
```
https://gcc.godbolt.org/z/GqhWs5

Expected: should accept, at least PCRE engine accepts such weird regexp https://regex101.com/r/ZxwTUe/1

**Comment by hanickadot** [comment]
What does the lazy modifier for the fixed-size loop mean?

**Comment by danlark1** [comment]
I think nothing, it was more of an issue I was checking against PCRE compliance. If you feel it is not important, just close the issue then :slightly_smiling_face:

**Comment by hanickadot** [comment]
non issue, there is no meaning in ?+ modifiers in exact repeat sequence
