### ISSUE TITLE
Observations from mariomka/regex-benchmark

### ISSUE THREAD

**Issue by bstaletic** [hanickadot/compile-time-regular-expressions#181]
For starters, I love this library. I ran code from here: https://github.com/mariomka/regex-benchmark/issues/37, on [this file](https://github.com/mariomka/regex-benchmark/blob/master/input-text.txt). Here's what I've found:

1. My first attempt was using `ctll::fixed_string`. It worked, but it produced a measurably slower binary.
2. After switching to the string literals as NTTP, the performance improved, so I wanted to test possessive instead of greedy matches. That also produced a slower binary, but only by a tiny bit.
3. The regex-benchmark repo also has [the optimized](https://github.com/mariomka/regex-benchmark#optimized) list. I've only taken a look at what Rust did to optimize. The only difference was [`unicode(false)`](https://github.com/mariomka/regex-benchmark/blob/optimized/rust/src/main.rs#L8), but I was also using CTRE without unicode.
4. How the hell is PHP so fast overall? And how does Javascript finish the third scan in just 2ms?

Finally, for my tests, I was using gcc 10.2.0 on i7-2620M.

Granted, the benchmarks in mariomka/regex-benchmark are not the best benchmarks in the world. Using just a single run isn't exactly how one benchmarks performance.

**Comment by hanickadot** [comment]
Ok ... is this is an issue?

**Comment by hanickadot** [comment]
What are the results of the benchmark.

**Comment by bstaletic** [comment]
> Ok ... is this is an issue?

Not really an issue. I just wanted to share what I've found, in case you're interested.

> What are the results of the benchmark?

```
49.8733 - 92
44.2878 - 5301
9.88212 - 5
```

Feel free to close the issue, whenever you like.

**Comment by hanickadot** [comment]
You can always write me on twitter, here I usually got a shock that there is a problem. How can I interpret the results?

**Comment by bstaletic** [comment]
> You can always write me on twitter, here I usually got a shock that there is a problem. 

Noted.

> How can I interpret the results?

The rows are `<time in milliseconds> - <number of matches in the file>`.
