### ISSUE TITLE
QString suport. 

### ISSUE THREAD

**Issue by XRay3D** [hanickadot/compile-time-regular-expressions#185]
How can I add QString support in CTRE?
Where do you need to fix the code?
I do not want to constantly use conversion in char array and back.

**Comment by hanickadot** [comment]
It should work automatically if the QString supports .begin(), and .end() iterators.

**Comment by Alcaro** [comment]
QString is utf16. If I'm reading the source correctly, CTRE only supports utf16 in fixed_string.

**Comment by hanickadot** [comment]
Unfortunately I don't have any QT installation available.

**Comment by hanickadot** [comment]
what it will print (if any error) if you try to use it?

**Comment by hanickadot** [comment]
ok, I have QT now, I will try to make it work for you :)

**Comment by XRay3D** [comment]
> ok, I have QT now, I will try to make it work for you :)

Thanks.

The compiler gives an error in "single-header/ctre.hpp":  
line 1212
static_assert(!is_array_v<_Elem> && is_trivial_v<_Elem> && is_standard_layout_v<_Elem>,
        "The character type of basic_string_view must be a non-array trivial standard-layout type. See N4861 "
        "[strings.general]/1.");

Maybe can add template parameters for customization for user containers, indicating the default from std.

**Comment by Ayxan13** [comment]
@XRay3D if you use [`QString::utf16()`](https://doc.qt.io/qt-5/qstring.html#utf16), it returns a `ushort` pointer to the buffer of QString. Then you can use that to construct a simple `basic_string_view<ushort>` and use with CTRE:

```
QString str = ...;
std::basic_string_view<ushort> view(str.utf16(), str.size());
```

**Comment by XRay3D** [comment]
> 
> 
> @XRay3D [`QString::utf16()`](https://doc.qt.io/qt-5/qstring.html#utf16) returns a `ushort` pointer to the buffer of QString. Then you can use that to construct a simple `basic_string_view<ushort>` and use with CTRE:
> 
> ```
> QString str = ...;
> std::basic_string_view<ushort> view(str.utf16(), str.size());
> ```

Ok, I'll try your use case.

**Comment by XRay3D** [comment]
I wrote a function and a wrapper class for ease of use. In the future I will rewrite it to std :: from_chars, when floating - point numbers become available in the GCC STD library
```c++
inline auto to_sv16(const QString& str)
{
    return std::u16string_view(reinterpret_cast<const char16_t*>(str.utf16()), str.size());
}

template <class T>
struct rxCap {
    T& cap;
    rxCap(T& cap)
        : cap { cap }
    {
    }
    operator QString() const { return QString(reinterpret_cast<const QChar*>(cap.data()), cap.size()); }
    auto toInt() const { return QString(reinterpret_cast<const QChar*>(cap.data()), cap.size()).toInt(); }
    auto toDouble() const { return QString(reinterpret_cast<const QChar*>(cap.data()), cap.size()).toDouble(); }

    operator int() const { return toInt(); }
    operator double() const { return toDouble(); }
};
template <class T>
rxCap(T) -> rxCap<T>;
```
