### ISSUE TITLE
Compiler internal error in MSVC

### ISSUE THREAD

**Issue by Ayxan13** [hanickadot/compile-time-regular-expressions#189]
This causes internal compiler error in MSVC:

```
#include <ctll/fixed_string.hpp>
#include <ctre.hpp>

int main() {
    static constexpr ctll::fixed_string range_regex{ LR"(s*(\d+)\s*-\s*(\d+)s*)" };
    ctre::match<range_regex>(L"");
}
```

tested with:
* ctre version 2.10
* VS 16.9.4
* Debug and Release, x86 and x64 builds
* /std:c++17 and /std:c++latest

Works fine on Clang and GCC. Here's a godbolt link showing all 3 compilers: https://gcc.godbolt.org/z/a3xGcb6of

**Comment by hanickadot** [comment]
You need to place the `range_regex` outside of the `main()` or you can use CNTTP syntax (`ctre::match<"regex">`) with your version of MSVC.

I recommend to report this error to MS.

**Comment by Ayxan13** [comment]
It's outside the main function in my project, still causes the error. The CNTTP syntax isn't available for C++17, so that's not a great replacement.

**Comment by hanickadot** [comment]
https://gcc.godbolt.org/z/Yjz15ofWP ... it must be outside of _any_ function
