### ISSUE TITLE
More Syntax errors

### ISSUE THREAD

**Issue by BenHanson** [hanickadot/compile-time-regular-expressions#19]
msvc branch again

static constexpr inline auto pattern = ctll::basic_fixed_string{ "[+]" };

gives "Regular Expression contains syntax error."

All other than ']', '\\' and '-' should be acceptable as normal characters?

**Comment by hanickadot** [comment]
Sorry, I didn't check for other control characters in a character set

**Comment by hanickadot** [comment]
Should be fixed, tests are in tests/matching2.cpp

**Comment by hanickadot** [comment]
backslash is only allowed if you do double backslash, same thing apply for - as it's is used for range construction
