### ISSUE TITLE
clang 12 seems to work fine with the C++20 syntax

### ISSUE THREAD

**Issue by oschonrock** [hanickadot/compile-time-regular-expressions#219]
Can correct readme to reflect that?

**Comment by hanickadot** [comment]
fixed

**Comment by oschonrock** [comment]
Another place? 


C++20 syntax

Currently, the only compiler which supports cNTTP syntax ctre::match<PATTERN>(subject) is GCC 9+.

**Comment by hanickadot** [comment]
Send PR.
