### ISSUE TITLE
Non-standard capturing group index order

### ISSUE THREAD

**Issue by matbech** [hanickadot/compile-time-regular-expressions#22]
Given this code:
```
static constexpr auto pattern = ctll::basic_fixed_string{ "((\\d)(\\d))" };
void Test()
{
	auto m = ctre::re<pattern>().match("12");
	auto a1v = m.get<1>().to_view();
	auto a2v = m.get<2>().to_view();
	auto a3v = m.get<3>().to_view();
}
```
I'm expecting that a1v="12", a2v="1", a3v="2", however the values are:
a1v="1"
a2v="2"
a3v="12"

I do have an idea why it is this way, but is this something that should be changed?

**Comment by hanickadot** [comment]
Fixed. Now it is calculated in opening parenthesis and not closing one.

**Comment by matbech** [comment]
Thank you
