### ISSUE TITLE
Cannot include dash (-) in character list

### ISSUE THREAD

**Issue by ryan-sammartino** [hanickadot/compile-time-regular-expressions#220]
I cannot get dash (-) included in a character list, for example: [[:word].-]+ (https://regex101.com/r/z9Qkui/2).

Here's what I get when I try C++17 style: https://gcc.godbolt.org/z/rb9xY38bd

I've tried moving the dash to the front and escaping it, to no avail.

**Comment by hanickadot** [comment]
You need to escape the backslash ...

`\\-`

because you are using c++ string literals and single backslash has the escape meaning, but for the literal and not the regex.

**Comment by ryan-sammartino** [comment]
*hangs head in shame*
