### ISSUE TITLE
probleme when extracting unicode word

### ISSUE THREAD

**Issue by Tudyx** [hanickadot/compile-time-regular-expressions#225]
## Environnement

- ubuntu 20.04
- gcc10 (I tried clang 13 and newer gcc version on compiler explorer)
- ctre/3.4.1

## Code to reproduce
```C++
#include <ctre-unicode.hpp>
#include <iostream>

int main()
{
    for (auto match : ctre::range<"\\p{Letter}+">("Tu es un génie"))
    {
        std::cout << match << std::endl;
    }
    return 0;
}
```
You can find these code on compiler explorer [here](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:5,endLineNumber:6,positionColumn:5,positionLineNumber:6,selectionStartColumn:5,selectionStartLineNumber:6,startColumn:5,startLineNumber:6),source:'%23include+%3Cctre-unicode.hpp%3E%0A%23include+%3Ciostream%3E%0A%0Aint+main()%0A%7B%0A++++%0A++++for+(auto+match+:+ctre::range%3C%22%5C%5Cp%7BLetter%7D%2B%22%3E(%22Tu+es+un+g%C3%A9nie%22))%0A++++%7B%0A++++++++std::cout+%3C%3C+match+%3C%3C+std::endl%3B%0A++++%7D%0A++++return+0%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:38.879825992387175,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:gsnapshot,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:ctre,ver:trunk)),options:'-std%3Dc%2B%2B20+-O3',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'x86-64+gcc+(trunk)+(C%2B%2B,+Editor+%231,+Compiler+%231)',t:'0')),k:27.786840674279503,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compiler:1,editor:1,fontScale:14,fontUsePx:'0',tree:'1',wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+gcc+(trunk)+(Compiler+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

## My problem

I expected this result : 
```
Tu
es
un
génie
```
But i got this one 
```
Tu
es
un 
g�
nie
```
I'm quite confident on my regex because i tested it online [here](https://regex101.com/r/ZajJQW/1).

I don't know if i used wrong the library or if this kind of things  is currently not supported or if it's a bug.

**Comment by Tudyx** [comment]
It works like a charm, thank you very much!  
Currently the documentation doesn't have an example on Unicode, maybe we could an example like this?

**Comment by hanickadot** [comment]
I'm currently quite busy, but PR is welcome.
