### ISSUE TITLE
Syntax error with [-d]

### ISSUE THREAD

**Issue by matbech** [hanickadot/compile-time-regular-expressions#23]
Error:
error C2338: Regular Expression contains syntax error.

Repo:
https://godbolt.org/z/06Dqch

Regex:
[-d]
https://regex101.com/r/qxTYfz/2

It seems ctre believes that the hyphen indicates a character range. But it has not special meaning in this case and should be treated as a single character.

Workaround:
```
[\-d]
```

**Comment by hanickadot** [comment]
should be fixed
