### ISSUE TITLE
Can't compile in Clang 12 or later with `-std=c++17`

### ISSUE THREAD

**Issue by remyjette** [hanickadot/compile-time-regular-expressions#234]
The readme states "clang 12.0+ (C++17 syntax, C++20 cNTTP syntax)"

But beginning with clang 12, just `#include <ctre.hpp>` causes a compilation error with `-std=c++17`

```
/opt/compiler-explorer/libs/ctre/main/include/ctll/parser.hpp:25:29: error: use of class template 'fixed_string' requires template arguments; argument deduction not allowed in template parameter
template <typename Grammar, ctll::fixed_string input, typename ActionSelector = empty_actions, bool IgnoreUnknownActions = false> struct parser { // in c++20
```

https://godbolt.org/z/Ph85TM7En

If I go back to clang 11, it works. If I switch to `-std=c++20`, it works. But on clang 12/13/trunk with `std=c++17` I get the above error.

**Comment by exief** [comment]
I'm also getting the same error

**Comment by jarzec** [comment]
Same issue here. I was about to create a twin of your PR 😄. Fortunately I decided to read through the existing ones first.
Let's hope the fix gets integrated soon.

**Comment by hanickadot** [comment]
should be fixed in latest `main`
