### ISSUE TITLE
Putting Unicode categories in square brackets followed by a single +, e.g. `[\p{L}]+`, doesn't compile

### ISSUE THREAD

**Issue by ivankp** [hanickadot/compile-time-regular-expressions#238]
As stated in the title, there appears to be a bug that doesn't allow `\p{}` or `\P{}` Unicode categories to be put in square brackets if followed by a `+` (the "one or more of these" regex token, not a literal +). Interestingly, either `[\p{L}]` or `[\p{L}]++` compile, but not `[\p{L}]+`. I've tried this with GCC 11.2 and GCC 11.1 with the same result.

Here's an example on Compiler Explorer: [link](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIAGwArKSuADJ4DJgAcj4ARpjEIAAcpAAOqAqETgwe3r4BwemZjgLhkTEs8YkpdpgO2UIETMQEuT5%2BQbaY9iUMjc0EZdFxCcm2TS1t%2BZ0KE4MRw5WjSQCUtqhexMjsHOYAzBHI3lgA1CZ7bg7EmAC0Xgx4aFgAdAipqefYJhoAgt8/EQIJxYTAiEBWZwA7FZficTgB6eEna4ETYME4QWKoTwrK7sEBKZrIBDnNxeJIAJXMZggJkCVkCbgA7nSACLWFbUz4QcnUpixUxmMycvYWBFIpkkADWCn%2B/zhiORmFRxHRmOxtFxBGuIAJmCJJIu5KpQtp9LpzItssC7MsnKF3N5Qv5guF5zFislxBlcthSpVaqxOLxusJW0NZMp1LNDLcH2hoRMkPZNo5XL22B5ST5AupIo9SNZAHlsEIomAOAAVE4AdSLFIA0icwGBm62W76fgqkSi0Rig5qQ3qDaTjdG6bH4xZE8m2dY0w6M1mc678%2BKTl6fb95eve6r%2BxqtTrh%2BHR1HTRO6V9Gcok9OkynbRZ7WZHdnnbmhWvFcXS%2BWq7W9ZNi2bZtp23b%2Bn26rBtq%2BJhsSZ4mjSl6BNgTAWreCYPnOdrppmTpmC6ebuuuv5lhW1Z1o2oEgR225%2Boqe6BoeQ7wRGY4XuaqHoTed4zo%2BL5viuxGiuum6ytuyYcGstCcIEvB%2BBwWikKgnBuPOlgnAoGxbJgZxmHsPCkAQmjSWsUogIEGj6JwkgKaZKmcLwCggNZJlKdJpBwLAMCICgqAsKkdAJOQlBoIFwWJMAXBcGYfB0AQCQuZiDmxBEzQAJ6cEZ4VsIIRYMLQWUeaQWAgkY4glfg1z1AAbpgLklZgqh1F4iUOYC3QObQeCxMQmUeFgDnangLDZZ5VAGMACgAGp4JgTJFqkjDjTIggiGI7BSGt8hKGoDm6Fw%2BiGMYGk2D1sQubAzBsCgsGkPViTavcUorGsqCpL0jU3EWewnDcszoOcrKClYlhmBo/01mItDOd0dS9C4DDuJ47R6GECwVFUehFFkAhTH4R2470QxY6MR21PUAj9JMqP5BT8NU30cykyMiQU3MBN6LMAys0s7NrNpmzbHosE7DwMlyfZJWqRwqhJP4Nz%2BJIJzAMgyAnDFzxmBi6mWNYpAnLghAkPphmGx4EX0MQZtcCsvDuVob2kBZVk2RwdmkGNkJcM8/gAJxJDFewQ5CgSSD7kKkIpymy85rnGaZazeX5GwEKkbWhRA4VBdb6P4EQ7M7Rt4jbfwgiKCo6glWLq1Mv1qTjZLHDydHDmy0WbUZ0CqBUCc8uK8rqvq5rvs6xAlu5wktv24nHnOwg%2BpYIk4Lu57Y1mEkzx7BoXBJArkL%2B2YkiBJvezSDHvBx7YCeO2ZLuWdZskcHs0ux05c9O83Zhv1fH9387R6mRnCSCAA%3D%3D%3D).

**Comment by hanickadot** [comment]
should be fixed, thanks for report

**Comment by ivankp** [comment]
Thank you for the very fast fix! It does work now.

**Comment by ivankp** [comment]
The fix seems to only work for `[\p{L}]` but not for `[\P{L}]`.

**Comment by hanickadot** [comment]
Now it should be ok :)
