### ISSUE TITLE
[MSVC] When building CTRE emits errors C2440 and C2912 on MSVC for amd_64 and x_86

### ISSUE THREAD

**Issue by Apriltanq** [hanickadot/compile-time-regular-expressions#244]
**System information**
Windows 10

**Issue description**
Hi, all
CTRE fails to build on MSVC build due to error C2440 and C2912. I have reproduced these errors in the latest fe build, Could you help look?

**Steps to reproduce**

1. open VS2019 x86 (or VS2019 x64)tools command
2. git clone https://github.com/hanickadot/compile-time-regular-expressions F:\gitP\hanickadot\compile-time-regular-expressions
3. cd F:\gitP\hanickadot\compile-time-regular-expressions\build_x86(or mkdir build_amd64
4. cd F:\gitP\hanickadot\compile-time-regular-expressions\build_amd64 )
5. set _CL_=/std:c++latest /utf-8 /permissive-
6. \\vcfs\Builds\msvc\fe\20220316.02\binaries.x86chk\bin\i386\CL.exe /std:c++latest /TP _unicode.i(or \\vcfs\Builds\msvc\fe\20220316.02\binaries.amd64chk\bin\amd64\CL.exe /std:c++latest /TP _unicode.i)

**Build.log:**

[buildfor64.log](https://github.com/hanickadot/compile-time-regular-expressions/files/8260839/buildfor64.log)
[buildfor86.log](https://github.com/hanickadot/compile-time-regular-expressions/files/8260842/buildfor86.log)

**Error info:**
F:\gitP\hanickadot\compile-time-regular-expressions\include\unicode-db/unicode-db.hpp(344,31): error C2440: 'initializing': cannot convert from 'std::_String_view_iterator<_Traits>' to 'const char *' [F:\gitP\hanickadot\compile-time-regular-expressions\build_x86\tests\ctre-test-_unicode.vcxproj]
                 with
                 [
                     _Traits=std::char_traits<char>
                 ]
       F:\gitP\hanickadot\compile-time-regular-expressions\include\unicode-db/unicode-db.hpp(344,19): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called [F:\gitP\hanickadot\compile-time-regular-expressions\build_x86\tests\ctre-test-_unicode.vcxproj]

F:\gitP\hanickadot\compile-time-regular-expressions\include\unicode-db/unicode-db.hpp(2994,1): error C2912: explicit specialization 'bool uni::cp_is<uni::category::co>(char32_t)' is not a specialization of a function template [F:\gitP\hanickadot\compile-time-regular-expressions\build_x86\tests\ctre-test-_unicode.vcxproj]

**other attachments**
[_unicodefor64.i.txt](https://github.com/hanickadot/compile-time-regular-expressions/files/8260888/_unicodefor64.i.txt)
[_unicodefor86.i.txt](https://github.com/hanickadot/compile-time-regular-expressions/files/8260889/_unicodefor86.i.txt)

**Comment by hanickadot** [comment]
Can you try PR `https://github.com/hanickadot/compile-time-regular-expressions/pull/246` if it fixes your problem?

**Comment by Apriltanq** [comment]
> Can you try PR `https://github.com/hanickadot/compile-time-regular-expressions/pull/246` if it fixes your problem?

@hanickadot I have followed the codes as PR which you have mentioned, and have generated patch files, the error C2912 was not appear, but popped up some other errors: C2923、C2955、C3861 etc.

**Comment by hanickadot** [comment]
Based on the build.log you seem to have a version different than the PR … as function `cp_is` is no longer there.

**Comment by Apriltanq** [comment]
> Based on the build.log you seem to have a version different than the PR … as function `cp_is` is no longer there.

@hanickadot Oh, yes, I tried again and changed all files, the bug disappeared, so this workaround is useful.

**Comment by hanickadot** [comment]
Thanks, fix is merged into main now.
