### ISSUE TITLE
Ctre doesn't work with "^(\\w+)"

### ISSUE THREAD

**Issue by beemibrahim** [hanickadot/compile-time-regular-expressions#251]
When using the slow "std::regex" it works :

```
std::string data = "WORD";
std::smatch matches;
	std::regex_search(data, matches, std::regex("^(\\w+)"));

	std::string match1 = matches[0];       // returns the match

```

When using fast ctre regex the variable " auto matches" is NULL  :

```
std::string data = "WORD";
std::string_view data_view = data;
    static constexpr auto elem = ctll::fixed_string{ "^(\\w+)" };
	auto matches = ctre::match<elem>(data_view);              // matches is null here

	std::string match1 = std::string(matches.get<1>());            // generates exception since matches is NULL
```

Pls fix this 

Im using Visual Studio with C++ 20

**Comment by hanickadot** [comment]
Works for me with latest Visual Studio:
https://compiler-explorer.com/z/xGszdMn69

**Comment by beemibrahim** [comment]
Hmm , okay I found out the reason it was failing was because my string had a "\r" at the end of it.

**Comment by beemibrahim** [comment]
> Works for me with latest Visual Studio: https://compiler-explorer.com/z/xGszdMn69

I've updated the question

**Comment by hanickadot** [comment]
You need to use proper function, with std::regex you used `std::regex_search`, if you want to have similar behaviour you need to use `ctre::search` not match.

**Comment by beemibrahim** [comment]
Whats the difference ??

**Comment by hanickadot** [comment]
Same as with `std::regex_match` and `std::regex_search`:

https://en.cppreference.com/w/cpp/header/regex

first matches entire input, second any part of the input

ctre has also `ctre::starts_with`

and range generating `ctre::range`, `ctre::tokenize`, `ctre::split`

**Comment by beemibrahim** [comment]
Okay
