### ISSUE TITLE
MSVC with -Zc:char8_t

### ISSUE THREAD

**Issue by tiagomacarios** [hanickadot/compile-time-regular-expressions#271]
The latest released version 3.7 fails to compile with MSVC when the -Zc:char8_t is used - https://microsoft.godbolt.org/z/n6hcdMood
I believe hanickadot/compile-time-regular-expressions@a4faab8abada9e8e22c4fcb1db9e3779e2d30a93 fixed the issue unintentionally - https://microsoft.godbolt.org/z/oezr6xx15  

Would it be possible to publish a new release with the fix?

**Comment by hanickadot** [comment]
the links doesn't work, probably some problém with the compiler explorer 🤷🏻‍♀️

**Comment by hanickadot** [comment]
v3.7.1 released
