### ISSUE TITLE
Bug: `lazy_repeat` drops `utf8_iterator` when matching a `char8_t` string

### ISSUE THREAD

**Issue by vector-of-bool** [hanickadot/compile-time-regular-expressions#285]
The following example reproduces the error:

```c++
// Compiles: 
match<"x+">(u8"x");
// Fails:
match<"x+?">(u8"x");
```

In the `lazy_repeat` evaluator, a nested call to `evaluate()` looks like this:

```c++
evaluate(begin, inner_result.get_end_position(), last, ...);
```

The type of `last`/`EndIterator` is `utf8_iterator::sentinel`, but `inner_result.get_end_position()` returns a `const char8_t*`, and these types are not equality-comparable.

Possibly needs a `static_cast<Itertaor>` around the call to `get_end_position`? I'm not sure if this would have some other unintended effects, or if there are other points in the code that will need to be similarly modified.

**Comment by hanickadot** [comment]
It should be fixed now :)

**Comment by vector-of-bool** [comment]
Excellent! Thank you for the quick fix!
