### ISSUE TITLE
Option to disable CTRE literals auto-activate

### ISSUE THREAD

**Issue by TinyTinni** [hanickadot/compile-time-regular-expressions#288]
Hi,
currently, I try to build my projects with activated C++20.  
Sadly, it doesn't work directly, as "CTRE_CNTTP_COMPILER_CHECK" gets activated which yields to some compatibility problems (in detail, there are conversion problems, as a custom object cannot be used to construct a ctll::fixed_string).

Therefore, I wanted to manually disable the new and shiny feature with pre-setting "CTRE_CNTTP_COMPILER_CHECK=0".  
This works well, as long as the CTRE literals stays deactivated. When I activate literlals, the compiler cannot find `ctre::regular_expression`.

 But because it is such a new and shiny compiler with C++20 support, it gets auto activated.

Therefore, is there a possibility to deactivate auto-enable of CTRE_ENABLE_LITERALS?  
Or would you think, that this is ok to add to the project? 
Something like CTRE_DISABLE_LITERALS in literals.hpp?
```cpp
#ifndef CTRE_DISABLE_LITERALS

#ifdef _MSC_VER
#ifdef _MSVC_LANG
#if _MSVC_LANG >= 202002L
#define CTRE_ENABLE_LITERALS
#endif
#else
#define CTRE_ENABLE_LITERALS
#endif
#endif
...
//clang/gcc etc.
#endif
```
Or is there another solution to achieve the "old"-behaviour?  

Info:
Compiler is MSVC 17.6 with C++17/20 activated.

**Comment by hanickadot** [comment]
Wouldn't be better to solve the compatibility problems? I would rather remove the non CNTTP approach at all as it was all hack around incomplete compilers. Can you elaborate more about the problem you are facing?

**Comment by hanickadot** [comment]
This should be easy. I will look into it.

**Comment by hanickadot** [comment]
Try it now.

**Comment by TinyTinni** [comment]
Oh thanks, I didn't mean that I needed exactly a std::array constructor, but it will definatly help.

I described the problem maybe a bit too rough. CTVE has a ctve::pattern, which contains a ctve::basic_string which is basically a std::array<char> but without access.

Having a std::array constructor might help, when I can add an implicit conversion from ctve::basic_string to the now easily constructable std::array. I tried it some days ago a implicit conversion of ctve::basic_sring -> fixed_string over a fixed size C array, but something went wrong (I cannot remember exactly if the constructor was wrong or the implicit cast/construction). I will re-try it tomorrow with the new constructor or the pointer constructor, so that a ctll::fixed_string can be implicit constructed from a ctve::basic_string and so that not every ctve expression needs an explicit conversion step.

Thank you really much for the help.

**Comment by hanickadot** [comment]
You can also invoke `ctll::fixed_string<N>(ctll::construct_from_pointer, ptr)` where `ptr` is just `const char *`

**Comment by TinyTinni** [comment]
> You can also invoke ctll::fixed_string<N>(ctll::construct_from_pointer, ptr) where ptr is just const char *

This is exactly what I will try. std::array might be too problematic with N and N+1

Adding something like

```cpp
template<size_t N>
class static_string{
   std::array<char, N+1> m_data;
//...
// new conversion function:
  operator ctll::fixed_string<N>(){
  return ctll::fixed_string<N>(ctll::construct_from_pointer{}, m_data.data());
}
//
};
```

**Comment by TinyTinni** [comment]
Works perfect, thank you ❤️

**Comment by hanickadot** [comment]
Btw totally unrelated, maybe it would be easier for the CTVE to just generate underlaying template CTRE is evaluating defined in [include/ctre/atoms.hpp](https://github.com/hanickadot/compile-time-regular-expressions/blob/main/include/ctre/atoms.hpp)
