### ISSUE TITLE
Regex benchmark compile error

### ISSUE THREAD

**Issue by Extra-Creativity** [hanickadot/compile-time-regular-expressions#290]
I find a small [benchmark](https://github.com/mariomka/regex-benchmark) to compare regex performance in different languages, and I'm trying to test it on this project. But this regex that is used to match Email seems not to compile:

```c++
R"([\w.+-]+@[\w.-]+\.[\w.-]+)"
```

Is this a bug?

**Comment by hanickadot** [comment]
you need to escape the dash inside character classes:
`[\w.+\-]+@[\w.\-]+\.[\w.\-]+`
It's a consequence of CTRE's parser design and also my decision to not have "special" weird cases. In CTRE dash inside character class always needs A-B to mark range. If it's meant as a character, you need to escape it.
