### ISSUE TITLE
gcc 7.2.0 compilation error

### ISSUE THREAD

**Issue by CapSel** [hanickadot/compile-time-regular-expressions#3]
$ make
g++ -std=c++1z -Wno-gnu-string-literal-operator-template -O3 -Iinclude -c math.cpp -o math.o
math.cpp: In function ‘int main()’:
math.cpp:211:2: error: non-constant condition for static assertion
  static_assert("2*(3+2)+32"_expr == 42);
  ^~~~~~~~~~~~~
In file included from include/static-decider.hpp:4:0,
                 from math.cpp:1:
math.cpp:211:16:   in constexpr expansion of ‘operator""_expr<char, '2', '*', '(', '3', '+', '2', ')', '+', '3', '2'>()’

... and the rest of errors

**Comment by CapSel** [comment]
https://gist.github.com/CapSel/246be1272771e47394341afc67ac87da#file-gcc-7-2-0-error-txt

**Comment by CapSel** [comment]
Not sure if the error explains all problems found by gcc...
Here is simplest solution I could find without understanding whole code yet:
https://gist.github.com/CapSel/e04479d760f948775b4603d33bde66e4#file-fixes-for-gcc-7-2-0-patch

**Comment by hanickadot** [comment]
Thank you for the report, it was fixed in rev 9d6db335299288fe3fbc334ed790f8ee0a7504aa.
