### ISSUE TITLE
interface with `std::optional`

### ISSUE THREAD

**Issue by TheClonerx** [hanickadot/compile-time-regular-expressions#302]
I always keep finding myself converting optional captures (ie. `([abcdef]+)?`) to `std::optional`s with something like the following:
```cpp
auto to_optional = [](auto const &capture) -> std::optional<std::string_view> {
  if (capture)
    return capture.view();
  else
    return std::nullopt;
};

auto const maybe_foo = to_optional(match_result.template get<1>());
```
I think it would be a good idea to add this functionality directly to the `regex_results` class template.

**Comment by hanickadot** [comment]
`regex_results` is already optional "like" type. I wonder how are you using `optional<std::string_view>` which is not contained in the `regex_results`. I do think about changing this part of API, but I would like to learn more about other's use-cases, thanks.

**Comment by TheClonerx** [comment]
I convert them to `std::optional` in order to return the results in struct members rather an `regex_results`.
Take this as an example:
```cpp
struct UserInfo {
  std::string_view user;
  std::optional<std::string_view> password;
};

std::optional<UserInfo> parse_userinfo(std::string_view str) {
  if (auto const &&[match, user, password] = ctre::match<"([a-z]+)(?::(.*))">(str); match)
    return UserInfo{ .user=user.view, .password=to_optional(password), };
  else
    return std::nullopt;
}```

**Comment by hanickadot** [comment]
ok, I would worry a bit about having views in some data structure tied to original input, but I can see usefulness of this

**Comment by TheClonerx** [comment]
> I would worry a bit about having views in some data structure tied to original input,

Of course it doesn't have to be for just `std::string_view`, ideally this would be implemented for `std::string` and numbers, making them analogous to the `to_view()`, `to_string()`, and `to_number()` member functions.

**Comment by hanickadot** [comment]
https://compiler-explorer.com/z/zMecxGvsM

**Comment by hanickadot** [comment]
I like this pattern:
```c++
std::optional<std::string_view> parse(std::string_view input) {
    return ctre::match<"[a-f]+">(input);
}
```

**Comment by hanickadot** [comment]
FYI: it was already implicitly convertible to string_view, so in your example, you can just write:

```c++
struct UserInfo {
  std::string_view user;
  std::optional<std::string_view> password;
};

std::optional<UserInfo> parse_userinfo(std::string_view str) {
  if (auto const &&[match, user, password] = ctre::match<"([a-z]+)(?::(.*))?">(str); match)
    return UserInfo{ .user=user, .password=password };
  else
    return std::nullopt;
}
```

**Comment by hanickadot** [comment]
Out of topic: I hope we will one day get rid of the `; match)` at end of the `if`

**Comment by TheClonerx** [comment]
Wow that was fast! Much appreciated.

> it was already implicitly convertible to string_view

I'm aware, I just prefer explicit conversions. :)
