### ISSUE TITLE
Cannot parse Unicode ranges after question mark as in `" ?[\p{L}]+"`

### ISSUE THREAD

**Issue by iboB** [hanickadot/compile-time-regular-expressions#305]
A regular expression of the form "something, question mark, range or Unicode chars" is not parsed correctly.

As seen in the example: https://gcc.godbolt.org/z/41ea8anqT

* `[\p{L}]+|[\p{N}]+` - works
* ` ?\p{L}+| ?\p{N}+` - works
* ` ?[\p{L}]+| ?[\p{N}]+` - doesn't compile even though it's valid

**Comment by hanickadot** [comment]
It should be fixed now

**Comment by hanickadot** [comment]
Thanks for reporting!

**Comment by iboB** [comment]
Thanks!
