### ISSUE TITLE
File include\ctre\wrapper.hpp failing to compile with LLVM 19

### ISSUE THREAD

**Issue by dyung** [hanickadot/compile-time-regular-expressions#307]
LLVM recently got a fix llvm/llvm-project@f46d146 for some template issues which are now causing the file include\ctre\wrapper.hpp to fail to compile with an error:
```
include\ctre\wrapper.hpp:173:27: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  170 |                 return Method::template exec();
      |                                         ^
1 error generated.
```
I filed a bug with llvm (llvm/llvm-project#94194) where it was confirmed that clang is correct and the code needs to be updated.

**Comment by hanickadot** [comment]
try with current mail please, I don't have currently llvm 19 available
