### ISSUE TITLE
Get match count in search_all 

### ISSUE THREAD

**Issue by msqr1** [hanickadot/compile-time-regular-expressions#310]
There is no way to get match count except using a range based for loop and increment an int. It would be nice to just get it via subtracting the begin iterator from the end instead of using a whole loop for that.

**Comment by hanickadot** [comment]
`ctre::search_all<RE>(subject)` models a forward range, it's evaluating the search lazily. To obtain number of matches you need to iterate or use some helper functions like `std::ranges::distance` which will do the iteration for you anyway as it's a forward range.
