### ISSUE TITLE
operator -> for match results

### ISSUE THREAD

**Issue by msqr1** [hanickadot/compile-time-regular-expressions#311]
When I access something of a regex_result type, I can access its string iterator member like this ```(*it).member```. Can we overload -> so that we have this? ```it->member```?

**Comment by hanickadot** [comment]
You can access the iterators in result type and capture groups via `.begin()` and `.end()` as there are two iterators for each group / result.

**Comment by msqr1** [comment]
I know, I used iterators to go over regex results, it is just a bit inconvenient that when I want to check the size, get the captures, I have to do ```(*it)``` before anything else. It would be good if we have a -> operator to avoid those parentheses, you know.

**Comment by hanickadot** [comment]
Show me example of what you are trying to do. For getting capture size there is a member function available, also for getting captures.

**Comment by msqr1** [comment]
Here is one:
```

  // Erase-remove idiom with regex
  auto res{ctre::search_all<"REGEX">(text)};
  size_t totalLen{};
  auto it{res.begin()};
  auto next{it};
  auto end{res.end()};
  while(it != end) {
    next = std::next(it);
    std::copy((*it).end(), next != end ? (*next).begin() : text.end(), (*it).begin() - totalLen);
    totalLen += (*it++).size();
  }
  text.resize(text.size() - totalLen);
  return *this;
```
 I have to copy to text.end() in the last match, but there is no way to get the match count (to check if this one is the last on) (#310) except for checking the iterator to see if the next one is the end. So I have to dereference the iterators, I can't find a way to use ranged based for loops.

**Comment by hanickadot** [comment]
For this usage `ctre::split<"REGEX">` is better:
https://compiler-explorer.com/z/f8E85Pvbj

**Comment by hanickadot** [comment]
Sorry for confusion, in your original description you didn't mention you are talking about `search_all` iterators. Yes the `operator->` can be useful.

**Comment by msqr1** [comment]
What does split do?

**Comment by hanickadot** [comment]
It iterates over subranges between matches.

**Comment by msqr1** [comment]
Oh... that is literally purrfect for this lol. What about the last one though, is it text.end?

**Comment by hanickadot** [comment]
Yes, last is `text.end()`, first is `text.begin()`

**Comment by msqr1** [comment]
Dang, that is actually so perfect!

**Comment by msqr1** [comment]
> Sorry for confusion, in your original description you didn't mention you are talking about `search_all` iterators. Yes the `operator->` can be useful.

Wait, so other iterators had -> before? Just not search_all, right?

**Comment by hanickadot** [comment]
No, I thought you are talking about `regex_results` and captures. They have iterator+sentinel pair for each capture group.

**Comment by msqr1** [comment]
Ohkay :)
