### ISSUE TITLE
Time complexity and matching method

### ISSUE THREAD

**Issue by msqr1** [hanickadot/compile-time-regular-expressions#313]
What is the matching method for this library? Is it the backtracking kind or a linear kind (like re2)? What is worst case time complexity for a expression?

**Comment by msqr1** [comment]
@hanickadot

**Comment by hanickadot** [comment]
backtracking, only dfa variant is linear, but for price of missing functionality

**Comment by msqr1** [comment]
I just learned regex, I don't actually know DFA and stuff. But basically, this engine is backtracking when it is not "DFA" variant? And linear when it is?
