### ISSUE TITLE
Create `<<` operator for `ctll::fixed_string`

### ISSUE THREAD

**Issue by alexios-angel** [hanickadot/compile-time-regular-expressions#318]
As you know in order to print `ctll::fixed_string` you need to define the ostream operator `<<`.

If you could make it:

```c++
friend std::ostream& operator<<(std::ostream& os, const fixed_string& str)
{
    os << std::string_view(reinterpret_cast<const char *>(str.data()), str.size() * sizeof(char32_t));
    return os;
}
```

I would really appreciate it.

**Comment by hanickadot** [comment]
what you are proposing is ill-formed, you are casting `char32_t` to `const char *` and it will print endian dependent 4 bytes to output ... it's definitelly a functionality I don't want to have in CTRE + I don't want to add dependency on <ostream>
