### ISSUE TITLE
import ctre compile error on MSVC

### ISSUE THREAD

**Issue by billhoffman** [hanickadot/compile-time-regular-expressions#324]
I have been testing the new install rules with a simple test. It works with clang.  However, I get a build error on windows.

Here is the code:

import std;
import ctre;

std::optional<std::string_view> extract_number(std::string_view s) noexcept {
      if (auto m = ctre::match<"[a-z]+([0-9]+)">(s)) {
        return m.get<1>().to_view();
    } else {
        return std::nullopt;
    }
}

int main()
{
  auto opt = extract_number("hello123");
  if (opt) {
    std::string s(*opt);
    std::cout << s << "\n";
  }
  return 0;
}

Here is the error:

C:\PROGRA~1\MICROS~1\2022\Preview\VC\Tools\MSVC\1442~1.343\bin\HOSTAR~1\arm64\cl.exe  /nologo /TP  -external:IZ:\Users\hoffman\Work\modules\realworld\install-windows\include -external:W0 /DWIN32 /D_WINDOWS /EHsc /Ob0 /Od /RTC1 -std:c++latest -MDd -Zi /showIncludes @CMakeFiles\ctre_hello.dir\ctre_hello.cpp.obj.modmap /FoCMakeFiles\ctre_hello.dir\ctre_hello.cpp.obj /FdCMakeFiles\ctre_hello.dir\ /FS -c Z:\Users\hoffman\Work\modules\realworld\ctre_hello\ctre_hello.cpp
Z:\Users\hoffman\Work\modules\realworld\install-windows\include\ctre\return_type.hpp(546): error C3861: 'find_captures': identifier not found
Z:\Users\hoffman\Work\modules\realworld\install-windows\include\ctre\return_type.hpp(546): note: the template instantiation context (the oldest one first) is
Z:\Users\hoffman\Work\modules\realworld\ctre_hello\ctre_hello.cpp(16): note: see reference to function template instantiation 'auto ctre::regular_expression<ctre::sequence<A,B>,ctre::match_method,ctll::list<ctre::singleline>>::operator ()<const char(&)[9]>(const char (&)[9]) noexcept const' being compiled
        with
        [
            A=ctre::repeat<1,0,ctre::set<ctre::char_range<97,122>>>,
            B=ctre::capture<1,ctre::repeat<1,0,ctre::set<ctre::char_range<48,57>>>>
        ]
Z:\Users\hoffman\Work\modules\realworld\ctre_hello\ctre_hello.cpp(16): note: see reference to variable template 'const ctre::regular_expression<ctre::sequence<A,B>,ctre::match_method,ctll::list<ctre::singleline>> match<ctll::fixed_string<14>{char32_t{91,97,45,122,93,43,40,91,48,45,57,93,43,41},unsigned __int64:14,bool:1}>' being compiled
        with
        [
            A=ctre::repeat<1,0,ctre::set<ctre::char_range<97,122>>>,
            B=ctre::capture<1,ctre::repeat<1,0,ctre::set<ctre::char_range<48,57>>>>
        ]
Z:\Users\hoffman\Work\modules\realworld\install-windows\include\ctre\wrapper.hpp(309): note: see reference to class template instantiation 'ctre::regular_expression<ctre::sequence<A,B>,ctre::match_method,ctll::list<ctre::singleline>>' being compiled
        with
        [
            A=ctre::repeat<1,0,ctre::set<ctre::char_range<97,122>>>,
            B=ctre::capture<1,ctre::repeat<1,0,ctre::set<ctre::char_range<48,57>>>>
        ]
Z:\Users\hoffman\Work\modules\realworld\install-windows\include\ctre\wrapper.hpp(178): note: while compiling class template member function 'auto ctre::regular_expression<ctre::sequence<A,B>,ctre::match_method,ctll::list<ctre::singleline>>::exec(const char *) noexcept'
        with
        [
            A=ctre::repeat<1,0,ctre::set<ctre::char_range<97,122>>>,
            B=ctre::capture<1,ctre::repeat<1,0,ctre::set<ctre::char_range<48,57>>>>
        ]
Z:\Users\hoffman\Work\modules\realworld\install-windows\include\ctre\wrapper.hpp(179): note: see reference to function template instantiation 'auto ctre::match_method::exec<Modifier,void,RE,const char*,ctre::zero_terminated_string_end_iterator>(IteratorBegin,IteratorEnd,RE) noexcept' being compiled
        with
        [
            Modifier=ctll::list<ctre::singleline>,
            RE=ctre::sequence<ctre::repeat<1,0,ctre::set<ctre::char_range<97,122>>>,ctre::capture<1,ctre::repeat<1,0,ctre::set<ctre::char_range<48,57>>>>>,
            IteratorBegin=const char *,
            IteratorEnd=ctre::zero_terminated_string_end_iterator
        ]
Z:\Users\hoffman\Work\modules\realworld\install-windows\include\ctre\wrapper.hpp(76): note: see reference to function template instantiation 'auto ctre::match_method::exec<Modifier,ResultIterator,RE,IteratorBegin,IteratorEnd>(IteratorBegin,IteratorBegin,IteratorEnd,RE) noexcept' being compiled
        with
        [
            Modifier=ctll::list<ctre::singleline>,
            ResultIterator=void,
            RE=ctre::sequence<ctre::repeat<1,0,ctre::set<ctre::char_range<97,122>>>,ctre::capture<1,ctre::repeat<1,0,ctre::set<ctre::char_range<48,57>>>>>,
            IteratorBegin=const char *,
            IteratorEnd=ctre::zero_terminated_string_end_iterator
        ]
Z:\Users\hoffman\Work\modules\realworld\install-windows\include\ctre\wrapper.hpp(72): note: see reference to alias template instantiation 'ctre::return_type<ctre::match_method::exec::result_iterator,RE>' being compiled
        with
        [
            RE=ctre::sequence<ctre::repeat<1,0,ctre::set<ctre::char_range<97,122>>>,ctre::capture<1,ctre::repeat<1,0,ctre::set<ctre::char_range<48,57>>>>>
        ]
Z:\Users\hoffman\Work\modules\realworld\ctre_hello\ctre_hello.cpp(24): error C2143: syntax error: missing ';' before 'return'
ninja: build stopped: subcommand failed.

**Comment by hanickadot** [comment]
This one will be tricky :( As I don't have any windows machine.

**Comment by billhoffman** [comment]
Can you try it on godbolt maybe?  I am also happy to try things if you have an idea.

**Comment by hanickadot** [comment]
I'm already looking into (just right now), I have installed windows into parallels.

**Comment by billhoffman** [comment]
Cool, thanks windows and parallels on a mac gives access to all the platforms!  That is what I am running. Thanks so much!

**Comment by hanickadot** [comment]
it should be fixed now :)

**Comment by hanickadot** [comment]
for some reason MSVC needs more symbols exported to work in TMP code completely inside the library, I expect that there can be some more

**Comment by billhoffman** [comment]
Works great on windows, but it broke on clang mac  `FAILED: CMakeFiles/ctre.dir/ctre.cppm.o CMakeFiles/ctre.dir/ctre.pcm 
/Users/hoffman/Work/llvm/llvm-inst/bin/clang++  -I/Users/hoffman/Work/modules/realworld/ctre/include -std=gnu++23 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -MD -MT CMakeFiles/ctre.dir/ctre.cppm.o -MF CMakeFiles/ctre.dir/ctre.cppm.o.d @CMakeFiles/ctre.dir/ctre.cppm.o.modmap -o CMakeFiles/ctre.dir/ctre.cppm.o -c /Users/hoffman/Work/modules/realworld/ctre/ctre.cppm
In file included from /Users/hoffman/Work/modules/realworld/ctre/ctre.cppm:25:
In file included from /Users/hoffman/Work/modules/realworld/ctre/include/ctre.hpp:4:
In file included from /Users/hoffman/Work/modules/realworld/ctre/include/ctre/literals.hpp:7:
/Users/hoffman/Work/modules/realworld/ctre/include/ctre/wrapper.hpp:159:79: error: cannot export redeclaration 'regular_expression' here since the previous declaration has module linkage
  159 | CTRE_EXPORT template <typename RE, typename Method, typename Modifier> struct regular_expression {
      |                                                                               ^
/Users/hoffman/Work/modules/realworld/ctre/include/ctre/wrapper.hpp:15:87: note: previous declaration is here
   15 | template <typename RE, typename Method = void, typename Modifier = singleline> struct regular_expression;
      |                                                                                       ^
1 error generated.
`

**Comment by hanickadot** [comment]
I really need to have proper modular test to catch this ... try it now.

**Comment by billhoffman** [comment]
Awesome!  Works on both now!   I am testing it with this `cmake_minimum_required(VERSION 3.29)

set(CMAKE_EXPERIMENTAL_CXX_IMPORT_STD "0e5b6991-d74f-4b3d-a41c-cf096e0b2508")

project(import_ctre)

find_package(ctre REQUIRED)

add_executable(ctre_hello ctre_hello.cpp)
target_link_libraries(ctre_hello PRIVATE ctre::ctre)
`

`import std;
import ctre;

std::optional<std::string_view> extract_number(std::string_view s) noexcept {
      if (auto m = ctre::match<"[a-z]+([0-9]+)">(s)) {
        return m.get<1>().to_view();
    } else {
        return std::nullopt;
    }
}

int main()
{
  auto opt = extract_number("hello123");
  if (opt) {
    std::string s(*opt);
    std::cout << s << "\n";
  }
  return 0;
}
`

**Comment by hanickadot** [comment]
Thanks for reporting! It's really cool to see `ctre` with `import`, I still can't get used to it.

**Comment by billhoffman** [comment]
Thanks for the help.  I will be covering this in my talk on Friday at CppCon.  I think this is the best realworld example of a package using modules.

**Comment by hanickadot** [comment]
Looking forward to watching video later, good luck with your talk!
