### ISSUE TITLE
Inconsistencies with `ctll::push<T...>`

### ISSUE THREAD

**Issue by robinmoussu** [hanickadot/compile-time-regular-expressions#38]
Both `ctre/pcre.hpp` and `ctre/simple.hpp` use `ctll::push<T...>` from `ctll/grammars.hpp` but neither files includes it. Given that those two files are generated, and the generator isn't available (cf #37), I can't fix it.

Furthermore, the uses of `ctll::push<T...>` should be consistent with the implementation of the overload set of the `move()` functions in `ctll/parser.hpp`. In that overload set, the resolution is done with `ctll::list<T...>` instead of the alias `ctll::push<T...>` witch is surprising since the parsing is using the return type of the functions declared in `ctre/pcre.hpp`/`ctre/simple.hpp`:

```
auto current_term = get_current_term<Pos>();
auto rule = decltype(grammar.rule(top_symbol,current_term))();
return move<Pos>(rule, current_term, stack, previous_subject);
```

**Comment by hanickadot** [comment]
I'm using "push" in the grammars instead of "list" because I want emphasize it's an action for parser.

**Comment by hanickadot** [comment]
parser.hpp changed and added missing include
