### ISSUE TITLE
[License] Re-license under BSL-1.0?

### ISSUE THREAD

**Issue by martinmoene** [hanickadot/compile-time-regular-expressions#46]
**ctre** is currently licensed under the [MIT license](https://opensource.org/licenses/MIT). 

Perhaps you want to reconsider this and re-license it under [Boost license (BSL-1.0)](https://opensource.org/licenses/BSL-1.0)?

Naturally [when ctre is part of the C++ standard](http://wg21.link/p1433), this question becomes less relevant ;)

My experience is that the Boost license is sometimes (often?) preferred as that _does not require that the license appear with executables or other binary uses of the library_, see this [note by Vinnie Falco on reddit](https://www.reddit.com/r/cpp/comments/8fmsm4/span_lite_singlefile_headeronly_version_of_a/dy7rq5d/). As a result I changed the _nonstd-lite_ projects to use the Boost license instead of MIT's.

**Comment by hanickadot** [comment]
I will think about it and decide soon :)

**Comment by hanickadot** [comment]
I decided to go with `apache license 2.0 with LLVM extension` as in issue #51
