### ISSUE TITLE
Warning for tuple_size and tuple_element with -Wall on clang++/g++ on Linux

### ISSUE THREAD

**Issue by alekratz** [hanickadot/compile-time-regular-expressions#48]
I get these warnings on g++ 8.2.1 and clang++ 7.0.1 when compiling on Linux with `-Wall` set:

```
ctre/ctre/include/ctre/return_type.hpp:229:34: warning: 'tuple_size' defined as a class template here but previously declared as a struct template [-Wmismatched-tags]
        template <typename... Captures> class tuple_size<ctre::regex_results<Captures...>> : public std::integral_constant<size_t, ctre::regex_results<Captures...>::size()> { };
                                        ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/array:350:5: note: did you mean class here?
    struct tuple_size;
    ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/utility:84:5: note: did you mean class here?
    struct tuple_size;
    ^

...

ctre/ctre/include/ctre/return_type.hpp:231:44: warning: 'tuple_element' defined as a class template here but previously declared as a struct template [-Wmismatched-tags]
        template <size_t N, typename... Captures> class tuple_element<N, ctre::regex_results<Captures...>> {
                                                  ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/array:359:5: note: did you mean class here?
    struct tuple_element;
    ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/utility:110:5: note: did you mean class here?
    struct tuple_element;
    ^
```

[It looks like a previous iteration of that file](https://github.com/hanickadot/compile-time-regular-expressions/blame/a722d7ebe44e8643028fa52b39db5104e1dd7325/include/ctre/return_type.hpp#L203) uses `struct` - is this because your compiler (MSVC?) uses `class` for those forward declarations instead? Do you know of any way to cleanly get rid of those warnings apart from editing the file itself?

**Comment by hanickadot** [comment]
It's problem with C++ standard in this case where struct/class is mismatched.
https://github.com/cplusplus/draft/issues/534
http://eel.is/c++draft/tuple.helper#lib:tuple_size,in_general

I'm not sure what I can do with it :( 
GCC and Clang I'm using with -Wall is not giving me any warning.

**Comment by beached** [comment]
I am not sure but does the name have to be std::tuple_size std::tuple_element.  I am fairly sure that specializing these is UB.  Plus, not including <tuple> may help compile time.

Giving these items another name or putting them into the ctre namespace may be effective.

**Comment by alekratz** [comment]
Well darn. Thanks for the insight. Feel free to close this issue if nobody is able to find a workaround.

FWIW I'm on Arch Linux, if anyone else runs in to this.

**Comment by hanickadot** [comment]
@beached `std::tuple_element` and `std::tuple_size` are customization points and you can overload them and they must be in `std::` namespace.

**Comment by hanickadot** [comment]
I also fixed inconsistency in the wording: https://github.com/cplusplus/draft/commit/6f34b0513ed6d974b86a27429f8f4d02a6c18b88
