### ISSUE TITLE
Incorrect use of __has_cpp_attribute

### ISSUE THREAD

**Issue by jamboree** [hanickadot/compile-time-regular-expressions#5]
There are snippets like below spilled over the code.
```
#if __has_cpp_attribute(__cpp_nontype_template_parameter_class)
```

But `__has_cpp_attribute` is for checking c++ attributes, e.g. `[[noreturn]]`.

Instead, what you need is:
```
#if __cpp_nontype_template_parameter_class
```

These are macros, it evaluates to false if not defined.

**Comment by hanickadot** [comment]
thank you very much! I didn't read the specification correctly and obviously it's working until there is a compiler which supports the feature :) fixed in master
