### ISSUE TITLE
Please create a CMakeLists.txt, define a interface target, and export/install the target

### ISSUE THREAD

**Issue by Neumann-A** [hanickadot/compile-time-regular-expressions#50]
Reasons:

a) clean integration into cmake projects. Use find_package(CTRE) to find the target
b) include it into another target with target_link_libraries(mytarget PRIVATE CTRE::CTRE) (whereever CTRE is located)
c) benefit from cmakes automatic compiler flags propagation e.g. mytarget would use c++17 because CTRE needs c++17

**Comment by hanickadot** [comment]
I'm not experienced with CMake enough. Can you send pull request with it?

**Comment by effolkronium** [comment]
Example for single header library: https://github.com/effolkronium/random/blob/master/CMakeLists.txt

;)
