### ISSUE TITLE
Relicensing to Apache License v2.0 (with LLVM extension)

### ISSUE THREAD

**Issue by hanickadot** [hanickadot/compile-time-regular-expressions#51]
I decided to relicense CTRE to Apache 2.0 with LLVM extension.

- [x]  send email / messages

- [x]  get approval from @0xdead4ead  (email)
- [x]  get approval from @Cqoicebordel  (twitter message)
- [x]  get approval from @hanickadot 
- [x]  get approval from @jgsogo (email)
- [x]  get approval from @leni536 (email)
- [x]  get approval from @matbech (email)
- [x]  get approval from @MerryMage (twitter message)
- [x]  get approval from @RabsRincon (email)
- [x]  get approval from @uilianries (email)

- [x]  change the license

**Comment by uilianries** [comment]
Hi!

Will it be available in 2.5?

**Comment by hanickadot** [comment]
I hope so, also with basic unicode support.

**Comment by uilianries** [comment]
Nice! :smile_cat:

**Comment by hanickadot** [comment]
Done.
