### ISSUE TITLE
MSVC: error C2247: 'ctll::fixed_string<156>::size' not accessible 

### ISSUE THREAD

**Issue by matbech** [hanickadot/compile-time-regular-expressions#52]
I get the following error with the latest update:
error C2247: 'ctll::fixed_string<156>::size' not accessible because 'ctll::basic_fixed_string<wchar_t,156>' uses 'private' to inherit from 'ctll::fixed_string<156>'

In the call to trampoline
```
	template <typename Subject = empty_subject> static constexpr auto trampoline_decide(Subject subject = {}) noexcept {
		// there will be no recursion, just sequence long as the input
		return trampoline_decide(subject, std::make_index_sequence<input.size()>());
	}
```

The code to reproduce looks like this:
static constexpr auto Pattern = ctll::basic_fixed_string{ LR"(^\s*(\d+)\s+:(\S):\$(\S+?)\$(\S+?)\$(\S+))" };

But it happens with every basic_fixed_string or fixed_string call.
Visual Studio 2019 RC1

**Comment by hanickadot** [comment]
try it now, it should be fixed, I refactored new fixed_string for unicode support and introduce compatibility layer and there was a problem with an inheritance

**Comment by matbech** [comment]
Thank you. It's fixed now.

**Comment by hanickadot** [comment]
Also, please use `ctll::fixed_string` from now on.
