### ISSUE TITLE
Build fail on MSVC latest and g++ 7.3

### ISSUE THREAD

**Issue by epicyclism** [hanickadot/compile-time-regular-expressions#53]
MSVC 16.0.0 fails with in a ICE something like,

1>test_ctre.cpp
1>common\compile-time-regular-expressions\include\ctre\wrapper.hpp(31): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>common\compile-time-regular-expressions\include\ctre\wrapper.hpp(70): note: see reference to class template instantiation 'ctre::RangeLikeType<Range>' being compiled
1>        with
1>        [
1>            Range=std::string &
1>        ]
1>test_ctre\test_ctre.cpp(12): note: see reference to function template instantiation 'auto ctre::regex_match_t<ctre::sequence<B,ctre::character<32>,A,ctre::character<33>>>::operator ()<std::string&>(std::string &) noexcept const' being compiled
1>        with
1>        [
1>            B=ctre::capture<1,ctre::plus<ctre::set<ctre::word_chars>>>,
1>            A=ctre::capture<2,ctre::plus<ctre::set<ctre::word_chars>>>
1>        ]
1>common\compile-time-regular-expressions\include\ctre\wrapper.hpp(31): fatal error C1001: An internal error has occurred in the compiler.
1>(compiler file 'd:\agent\_work\3\s\src\vctools\Compiler\CxxFE\sl\p1\c\symbols.c', line 24466)

Code compiles with a CTRE version from around Feb 15. I've reported the ICE to Microsoft.

Also I tried g++ 7.3.0 on Ubuntu 18.04. Everything fails to build here too, but in a different way. This could be my finger trouble. Anyway 'make' in the ctre directory will do it, but I've tried a simple test file and get the same result.

paul@fasolt:~/compile-time-regular-expressions$ make
time g++ -std=c++17 -Iinclude -O3 -pedantic -Wall -Wextra  -MMD -c tests/range.cpp -o tests/range.o
In file included from include/ctre/../ctll/parser.hpp:4:0,
                 from include/ctre/../ctll.hpp:4,
                 from include/ctre/literals.hpp:4,
                 from include/ctre.hpp:4,
                 from tests/range.cpp:1:
include/ctre/../ctll/fixed_string.hpp:176:62: error: parameter ‘<anonymous>’ includes reference to array of unknown bound ‘const T []’
  template <typename T> constexpr fixed_string(const T (&)[]) noexcept {
                                                              ^~~~~~~~
Command exited with non-zero status 1
0.71user 0.07system 0:01.60elapsed 49%CPU (0avgtext+0avgdata 90368maxresident)k
35344inputs+8outputs (132major+19660minor)pagefaults 0swaps
Makefile:31: recipe for target 'tests/range.o' failed
make: *** [tests/range.o] Error 1

This is gcc 7.3.0.

**Comment by hanickadot** [comment]
GCC 7.2+ is working again (fixed in latest master)

**Comment by epicyclism** [comment]
Confirmed. Thanks!

**Comment by hanickadot** [comment]
MSVC problem was with SFINAE check and operator() in std::true_type / std::false_type, I found workaround in a2997436813c56d178111e94f49656d855f79532. Please confirm fix in MSVC.

**Comment by epicyclism** [comment]
Confirm MSVC fix, builds and runs as before. Thank you again. 

I'll update the MSVC bug report since they will no longer be able to easily reproduce their ICE.

**Comment by hanickadot** [comment]
Please point them to the commit a2997436813c56d178111e94f49656d855f79532. Have a nice day!

**Comment by epicyclism** [comment]
Have done, tremendous service from you. Enjoy your weekend.
