### ISSUE TITLE
constexpr with function arguments over NTTPs

### ISSUE THREAD

**Issue by johelegp** [hanickadot/compile-time-regular-expressions#55]
It seems that the current implementation uses NTTPs, which means that using complex regexes become troublesome or impossible due to resource consumption. With GCC9+ supporting `std::is_constant_evaluated()`, a pure constexpr implementation that takes the regex as a function argument should be possible. That shouldn't consume as much resources as the NTTP implementation, and error messages should improve if exceptions were to be thrown at the point of error. After all, the current implementation simply `static_assert`s at a fixed position, giving no clue as to what might have gone wrong.

**Comment by hanickadot** [comment]
I don't see this as an issue, can you elaborate more?

**Comment by hanickadot** [comment]
If we want to support structured binding, which is really loved feature, we need to build different type for each pattern match/search output. I don't see any other way how to build a type based on a function argument.

**Comment by hanickadot** [comment]
I recommend reading the code, you will find that everything is template-based with minimum of constexpr, changing that is making a completely new library

**Comment by johelegp** [comment]
> I don't see this as an issue, can you elaborate more?

Unfortunately, the [email regex from the HTML5 spec](https://html.spec.whatwg.org/multipage/input.html#e-mail-state-(type%3Demail)) causes resource exhaustion: https://godbolt.org/z/3sl60B. The individual lines of the regex compile fine, though.

> I recommend reading the code, you will find that everything is template-based with minimum of constexpr, changing that is making a completely new library

You're right. I also thought that it was implementable, but non-transient `constexpr` allocations won't make it for C++20, which is required.
