### ISSUE TITLE
MSVC: first.hpp: error C2664: cannot convert argument 2 from 'ctll::list' to 'ctll::list<>

### ISSUE THREAD

**Issue by matbech** [hanickadot/compile-time-regular-expressions#57]
One of the latest commits caused this regression with MSVC 16.1 Preview 2:

29>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(244,9): **error C2664:  'auto ctre::first<>(ctll::list<>,ctll::list<>) noexcept': cannot convert argument 2 from 'ctll::list<A>' to 'ctll::list<>'**
29>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(244,9): error C2664:         with
29>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(244,9): error C2664:         [
29>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(244,9): error C2664:             A=ctre::negative_set<ctre::space_chars>
29>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(244,9): error C2664:         ]

**Comment by hanickadot** [comment]
I need thee pattern you are using.

**Comment by hanickadot** [comment]
should be fixed in 42e26963a4b1e186923e1ad8408d3d0ba5d6b4d0, let me know

**Comment by matbech** [comment]
I get this error now:
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(290,10): error C2664:  'void ctre::negative_helper<CB&>(ctre::negative_set<>,ctre::point_set<2>::populate::<lambda_1>&,int64_t)': cannot convert argument 1 from 'Head' to 'ctre::negative_set<>'
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(290,10): error C2664:         with
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(290,10): error C2664:         [
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(290,10): error C2664:             CB=ctre::point_set<2>::populate::<lambda_1>
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(290,10): error C2664:         ]
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(290,10): error C2664:         and
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(290,10): error C2664:         [
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(290,10): error C2664:             Head=ctre::space_chars
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(290,10): error C2664:         ] (compiling source file Parser\GXSEnterpriseParser.cpp)
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(290,30): message :  No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called (compiling source file Parser\GXSEnterpriseParser.cpp)
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(422): message :  see reference to function template instantiation 'void ctre::negative_helper<ctre::space_chars,,ctre::point_set<2>::populate::<lambda_1>>(ctre::negative_set<ctre::space_chars>,CB &&,int64_t)' being compiled
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(422): message :         with
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(422): message :         [
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(422): message :             CB=ctre::point_set<2>::populate::<lambda_1>
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(422): message :         ] (compiling source file Parser\GXSEnterpriseParser.cpp)
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(427): message :  see reference to function template instantiation 'void ctre::point_set<2>::populate<ctre::space_chars>(ctre::negative_set<ctre::space_chars>)' being compiled (compiling source file Parser\GXSEnterpriseParser.cpp)
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(428): message :  see reference to function template instantiation 'void ctre::point_set<2>::populate<ctre::space_chars>(ctre::negative_set<ctre::space_chars>)' being compiled (compiling source file Parser\GXSEnterpriseParser.cpp)
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(432): message :  see reference to function template instantiation 'void ctre::point_set<2>::populate<A>(ctll::list<A>)' being compiled
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(432): message :         with
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(432): message :         [
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(432): message :             A=ctre::negative_set<ctre::space_chars>
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(432): message :         ] (compiling source file Parser\GXSEnterpriseParser.cpp)
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(436): message :  see reference to function template instantiation 'void ctre::point_set<2>::populate<A>(ctll::list<A>)' being compiled
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(436): message :         with
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(436): message :         [
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(436): message :             A=ctre::negative_set<ctre::space_chars>
1>C:\Projects\Libraries\ctre\compile-time-regular-expressions\include\ctre\first.hpp(436): message :         ] 

Pattern: LR"(^(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\d+)\s+(\d+)\s*$)"

**Comment by hanickadot** [comment]
try current master #14b74584f9aadc004cf1af58b243ea4ee0ca32c2

**Comment by matbech** [comment]
I do get the same error with another pattern:
LR"(^([-dlsDLS][-rwxstlRWXSTL]{9}[+]?)\s+(\d+)?\s+(\S+)?\s+(.*?)?\s+(\d+)\s+(\d{1,2})\.\s([^\s,\.]{3,4})\.?,?\s((\d{4,4})|(\d{1,2}):(\d{2,2}))\s)"

**Comment by hanickadot** [comment]
try 6478da9b20f415d5883232ba5ff564263dad41ac

**Comment by matbech** [comment]
This fixed it. Thank you.

**Comment by hanickadot** [comment]
Thank you for reporting the issue.
