### ISSUE TITLE
warning C4244:  'initializing': conversion from 'int64_t' to 'size_t', possible loss of data

### ISSUE THREAD

**Issue by matbech** [hanickadot/compile-time-regular-expressions#58]
When the arch is 32-bit (size_t = 32 bits), I get the following warning:
warning C4244:  'initializing': conversion from 'int64_t' to 'size_t', possible loss of data 

When using something like that:
	const auto results = ctre::re<Pattern1>().search(begin, end);

The pattern does not seem to matter. But it is triggered with this one:
LR"(^([-dlsDLS][-rwxstlRWXSTL]{9}[+]?)\s*(\d+)?\s+(\S+)?\s+(.*?)?\s+(\d+|\d+\.\d+\S)\s+([A-Za-z][a-z][a-z])\s+(\d{1,2})\s+((\d{4,4})|(\d{1,2})[:\.](\d{2,2}))\s)"

**Comment by hanickadot** [comment]
Can you minimize the pattern? I have only compiler-explorer to test it and I'm hitting timeouts.

**Comment by hanickadot** [comment]
without more info like line and file I can't help you, I'm unable to trigger this warning

**Comment by hanickadot** [comment]
warning fixed

**Comment by matbech** [comment]
Confirmed. Thank you.
