### ISSUE TITLE
MSVC: linker stuck for hours

### ISSUE THREAD

**Issue by matbech** [hanickadot/compile-time-regular-expressions#59]
With the latest optimization, the MSVC linker (64-bit version, compiling 32-bit code) didn't finish after more than one hour (using LTCG). The memory usage is at 2-4GB, CPU usage is constantly around 70-80%. Before, the linker took a couple of minutes for the same code.

Does setting CTRE_DISABLE_GREEDY_OPT help in this case?

**Comment by hanickadot** [comment]
yes

**Comment by matbech** [comment]
I don't think it is optimal that the user has to find an undocumented define first to be able to link the code. Maybe if the issue is more common, the optimization should be disabled by default.

**Comment by hanickadot** [comment]
https://github.com/hanickadot/compile-time-regular-expressions/releases/tag/v2.6.3

it's documented here

**Comment by hanickadot** [comment]
MSVC never produced optional code with CTRE, is just partially supported as there are open bugreport s for MSVC frontend, on other platforms (clang, gcc) the optimization is having virtually no impact and it's generating much better code. 

We can discuss it later, currently I'm occupied by something more important. But please don't use issues here as discussion forum. I'm trying to have open issues only for thing I can fix.

**Comment by hanickadot** [comment]
To explain myself: I'm recently stressed. And I prefer to fix immediate errors. This is something which probably I can't solve. So I'm sorry for being harsh on you. But the optimization will help many and that's reason I did it. Please send bugs to MSVC.

**Comment by matbech** [comment]
I do understand your situation. I wasn't expecting anything, I just wanted to share my thoughts.  I appreciate all the effort you put into CTRE. 
I did file several bug reports with reproducible cases to MSVC in the past, but I lost motivation since these bug reports generally receive very little attention and some of the issues have not been fixed after more than a year.
