### ISSUE TITLE
Unnecessary escaping of otherwise special characters in square brackets

### ISSUE THREAD

**Issue by johelegp** [hanickadot/compile-time-regular-expressions#60]
According to http://www.pcre.org/current/doc/html/pcre2pattern.html#SEC9, between `[` and `]`:
- You don't need to escape `^` for it to be considered literally if its not after the `[`, where it has a special meaning.
- Similarly, you need to escape `-` for it to considered literally even if it's in a place where it unambiguously can't be used to define a range.

See example: https://godbolt.org/z/8v6cu7. It seems that you also need to escape `|`, even though it has no special meaning anywhere between square brackets.
> The only metacharacters that are recognized in character classes are backslash, hyphen (only where it can be interpreted as specifying a range), circumflex (only at the start), opening square bracket (only when it can be interpreted as introducing a POSIX class name, or for a special compatibility feature - see the next two sections), and the terminating closing square bracket. However, escaping other non-alphanumeric characters does no harm.

**Comment by hanickadot** [comment]
Should be fixed now.

**Comment by hanickadot** [comment]
Thank you for reporting the issue.

**Comment by johelegp** [comment]
Thank you.

**Comment by johelegp** [comment]
Seems like it's not working: https://godbolt.org/z/c5HCj3

**Comment by hanickadot** [comment]
I removed the special case allowing [-] and [-something], currently the LL1 grammar is designed in a way which doesn't allow to fixing this, to avoid further confusion, this is no longer supported, maybe in future with a big refactoring of the grammar or parser I will revisit this.

**Comment by hanickadot** [comment]
I tried it, but unsuccessfully.
