### ISSUE TITLE
Links to talks

### ISSUE THREAD

**Issue by johelegp** [hanickadot/compile-time-regular-expressions#62]
It'd be nice if the README provided links to the talks you've given on this library, and maybe other existing resources on it aswell. Is [the CppCon 2018 one](https://www.youtube.com/watch?v=QM3W36COnE4 "CppCon 2018: Hana Dusíková “Compile Time Regular Expressions”") the most up-to-date?

**Comment by cppguru** [comment]
compile-time.re has all the links I think.

**Comment by johelegp** [comment]
Excellent. Thank you. That's probably what should go into the README.

**Comment by cppguru** [comment]
And that page link to the README for a demonstration of recursion. ;)
