### ISSUE TITLE
ctll\grammars.hpp(86): error C1075:  '{': no matching token found 

### ISSUE THREAD

**Issue by matbech** [hanickadot/compile-time-regular-expressions#63]
include\ctll\grammars.hpp(86): error C1075:  '{': no matching token found

In this line:
	template <auto V, typename = std::enable_if_t<!(Set == V) || ... || false)>> constexpr inline neg_set(term<V>) noexcept;

using MSVC 16.1.0 Preview 3

**Comment by matbech** [comment]
Thank you.

**Comment by hanickadot** [comment]
Sorry, this was overlook on my side.
