### ISSUE TITLE
I didn't find any instructions on how to build this Library on MSVC.

### ISSUE THREAD

**Issue by QuellaZhang** [hanickadot/compile-time-regular-expressions#65]
Hi hanickadot, thanks for this library at first.

We want to build this lib on MSVC, but I didn't find any instructions. Could you tell me where I can get it? Or can you provide the build steps for me? If you need any other question please let me know. Thank you very much.

Our environment: VS 2017 + Windows Server 2016

**Comment by hanickadot** [comment]
If you have MSVC at least version 15.8.8. Just include the `single-header/ctre.hpp` in your code and compile your project with `/std:c++latest`. The library is header only.

**Comment by QuellaZhang** [comment]
@hanickadot,  thank you for your reply. Actually, I mean we want to treat this lib as a standalone project that can be built separately in MSVC, instead of how to use this lib in the other projects.

This is a good project for constexpr, so we (MSVC team) are trying to add this project to our RWC (real world code) testing to detect regressions from MSVC, can you help provide build document? Like this: https://www.tensorflow.org/install/source_windows. Thank you in advance.

**Comment by hanickadot** [comment]
Ah, sorry. I do understand you now. I near future I should have a cmake project for the library and tests. Or if you want, just compile all tests: `tests/*.cpp` (not the subdirectories). Try to use latest tag, sometimes due my recklessness I break the master branch.

**Comment by QuellaZhang** [comment]
Glad to hear that, waiting for you to complete cmake project. :)

**Comment by hanickadot** [comment]
Hi, sorry for delay...

build with cmake with `-DENABLE_CTRE_SELF_TEST=ON` and then build target `ctre_self_test`

Please let me know if it's enough for you.

**Comment by QuellaZhang** [comment]
Wow, thank you very much. Please keep this issue active, I will have a comment once I get result.

**Comment by hanickadot** [comment]
@QuellaZhang just pinging you to ask for status :)

**Comment by JonCavesMSFT** [comment]
@QuellaZhang -- it there any update on this? I would love for this library to be added to our suite

**Comment by QuellaZhang** [comment]
@JonCavesMSFT. The RWC OSS migration is nearing completion, and I believe it is coming soon.

**Comment by QuellaZhang** [comment]
Hey, sorry for the late. We have added the project to our test suite. JonCaves provides patch to fix issues under c++20. Feel free to close this issue.
patch: [ctre_test_error_c3688.patch.txt](https://github.com/hanickadot/compile-time-regular-expressions/files/4380306/ctre_test_error_c3688.patch.txt)
