### ISSUE TITLE
"Regular Expression contains syntax error"  on YYYY-MM-DD pattern

### ISSUE THREAD

**Issue by philong6297** [hanickadot/compile-time-regular-expressions#70]
I have a regex to check valid YYYY-MM-DD date with the separators between numbers can be `-`, `.` or `/`. It is strange for me when its fail on pattern `[-\.\/]` but it works fine on non-captured group `(?:-|\.|/)`.  

The following regexes made assertion failed:
- C++ 17
- clang 8.0.0, gcc 9.1
- [compiler explorer](https://godbolt.org/z/g_NvOg)
```cpp
#include <ctre.hpp>
namespace {
    constexpr ctll::fixed_string A 
    = R"(^(?:\d{4})[-\.\/](?:0[1-9]|1[0-2])[-\.\/](?:0[1-9]|[12]\d|3[01])$)";
    constexpr ctll::fixed_string B 
    = R"(^(?:\d{4})(?:-|\.|\/)(?:0[1-9]|1[0-2])(?:-|\.|\/)(?:0[1-9]|[12]\d|3[01])$)";
    constexpr ctll::fixed_string C 
    = R"(^(?:\d{4})(?:-|\.|/)(?:0[1-9]|1[0-2])(?:-|\.|/)(?:0[1-9]|[12]\d|3[01])$)";

}

auto f() {
    ctre::match<A>("test"); //error
    ctre::match<B>("test"); //error
    ctre::match<C>("test"); //fine
}
```

**Comment by hanickadot** [comment]
* Minus `-` is special char in a character class and must be escaped inside `[...]`
* also you don't need to escape dot `.` as it's not a special char inside a character class
* slash `/` is not special char at all inside or outside a character class

https://godbolt.org/z/rH-Q5b

**Comment by Bu11etmagnet** [comment]
Isn't `-` supposed to lose its special status inside `[...]` when in first or last position, i.e. 

> The following all specify the same    class of three characters: `[-az]`, `[az-]`, and `[a\-z]`

(from `perldoc perlre`).

**Comment by hanickadot** [comment]
Ok, this is known problem and currently without major redesign of parsing of the pattern I can't fix have same behavior. As my longterm goal is to switch to ECMAscript RE syntax this is not priority for me until I will found that the behavior should be same as in perl.

Please treat this as a different dialect. Sorry for inconvinience.

**Comment by johelegp** [comment]
@hanickadot Consider documenting this.
