### ISSUE TITLE
Named capture group

### ISSUE THREAD

**Issue by FranklinYu** [hanickadot/compile-time-regular-expressions#71]
This is a feature request. I haven’t research the feasibility.

See https://www.pcre.org/current/doc/html/pcre2syntax.html#SEC13.

**Comment by hanickadot** [comment]
It's already implemented:
https://compiler-explorer.com/z/cDwR0B

**Comment by jeanga** [comment]
Hi Hana, 
Thank you for implementing the named captured groups! 👍 

Your exemple on compiler explorer uses a c++20 syntax: r.get<"name">

I struggle to use the c++17 syntax with:
static constexpr auto name_group = ctll::fixed_string{"name"};
and then use r.get<name_group>()

Is that the syntax you expect?
Thanks!
Jean
PS: I am using MSVC  19.26.28619

**Comment by hanickadot** [comment]
I actually think this is not implemented, only char by char name groups. Will fix this today.

**Comment by hanickadot** [comment]
Created issue #96

**Comment by hanickadot** [comment]
Now it will work, changed in: dc91158187e768170b6b3d763b6e0881290c0fc5

**Comment by jeanga** [comment]
Well, I am sure you have implemented the change but MSVC has trouble compiling it:
[build] ..\main.cpp(50): fatal error C1001: Internal compiler error.
[build] (compiler file 'msc1.cpp', line 1532)
[build]  To work around this problem, try simplifying or changing the program near the locations listed above.
[build] If possible please provide a repro here: https://developercommunity.visualstudio.com 
[build] Please choose the Technical Support command on the Visual C++ 
[build]  Help menu, or open the Technical Support help file for more information
[build] INTERNAL COMPILER ERROR in 'C:\PROGRA~2\MICROS~2\2019\Preview\VC\Tools\MSVC\1426~1.286\bin\Hostx64\x64\cl.exe'
[build]     Please choose the Technical Support command on the Visual C++
[build]     Help menu, or open the Technical Support help file for more information

I'll report the issue to Microsoft and will update this issue with the URL to the report.
Any way, many many thanks for your amazing work on this library. Really impressive!

**Comment by hanickadot** [comment]
Did you use dc91158187e768170b6b3d763b6e0881290c0fc5? There was not nice error in it, try latest master.

**Comment by hanickadot** [comment]
Unfortunetelly I can't help you as my only MSVC is on https://compiler-explorer.com and there is 19.24 the latest.

**Comment by jeanga** [comment]
Reported here: https://developercommunity.visualstudio.com/content/problem/973790/fatal-error-c1001-internal-compiler-error-compiler.html.
Thank you for your help!
