### ISSUE TITLE
(a)\1 silently does the wrong thing

### ISSUE THREAD

**Issue by Alcaro** [hanickadot/compile-time-regular-expressions#77]
```
#include <ctre.hpp>

static constexpr auto re = ctll::fixed_string{"(a)\\1"};

bool w(const char * x)
{
    auto y = ctre::match<re>(x);
    return (bool)y;
}

int main()
{
    printf("match:%d\n", w("aa"));
    printf("match:%d\n", w("a1"));
}
```
https://godbolt.org/z/mGg5R1

-> it matches "a1", not "aa". To get the expected behavior, I need (a)\g{1}.

If your Desatomat parser can't represent the usual backreference syntax, I recommend rejecting \1 with a static_assert pointing to the right syntax, rather than silently doing something unexpected. Same goes for those unsupported letters, like \A and \Z; better compile error than unexpected runtime behavior.

(main() is poorly optimized in that program, but hardcoding the regexes' input isn't really the intended usecase, so I'm not sure if it's worth fixing. Bad optimization is more of a compiler bug than a CTRE bug, anyways.)

**Comment by hanickadot** [comment]
fixed in 96de8f7a519b61abd4ef53ec37cd89565880aa50, thanks for reporting the issue

**Comment by Alcaro** [comment]
Ah yes, that's a valid solution too. It will give different results from PCRE on (a)(a)(a)(a)(a)(a)(a)(a)(a)(a)\10, but exceeding 3-4 capture groups is super rare anyways, so this is fine.

**Comment by hanickadot** [comment]
I'm only accepting \1 ... \9 if you want more, use \g{N}

**Comment by alexios-angel** [comment]
With the help of AI, I have remade the Desatomat tool. See link below:

https://github.com/alexios-angel/Tablewright
