### ISSUE TITLE
Returning all matches in a string

### ISSUE THREAD

**Issue by AntonioCS** [hanickadot/compile-time-regular-expressions#79]
Hey,
I am trying to use `ctre::range` to give me all the matches in a string.
I have the following code: 
```
void match_all(std::string_view input) noexcept {
    for (auto match : ctre::range<".+(\\{\\{|\\{%|\\{#(\\-|~)?).+">(input)) {
        std::cout << match.get<1>().to_view() << "\n";
    }
}
...

match_all("Hello {{ name }}{{ surname }}");

```

I was hoping to get at least 2 outputs, the first `{{` and then the second `{{`.
I only see the first one and then I get nothing else.
Am I doing something incorrectly?

**Comment by hanickadot** [comment]
Hey, this is not issue, range function is going to "eat" as much as possible, remove `.+` at the end.

**Comment by AntonioCS** [comment]
Oh, ok sorry. Is there any place in the docs where I can see more examples of the usage of this?
But you are totally correct, it was indeed my fault with the regex, it does work now.

**Comment by hanickadot** [comment]
I'm glad it helped. Unfortunately I don't have any better documentation, yet.

**Comment by AntonioCS** [comment]
Ok, thank you for you help.
