### ISSUE TITLE
Including ctre.hpp produces errors in MSVC

### ISSUE THREAD

**Issue by AntonioCS** [hanickadot/compile-time-regular-expressions#81]
Hey,

I installed CTRE via vcpkg and I can include the file just fine, but when I do I get the following:

![image](https://user-images.githubusercontent.com/1086401/67658291-19add280-f951-11e9-996c-29f6cf2e92e1.png)

Do I need to include something else? Create a special `#define`?
To note that these errors appear as soon as I include the file `ctre.hpp`, there is no ctre regex code just the file.

Here is MSVC info:
```
Microsoft Visual Studio Community 2019
Version 16.3.6
VisualStudio.16.Release/16.3.6+29418.71
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA806
Microsoft Visual C++ 2019
```

**Comment by hanickadot** [comment]
I don’t support vcpkg, as there is no automatic way of building pipeline done. Use master branch single header version.

**Comment by AntonioCS** [comment]
![Sad](https://www.thewrap.com/wp-content/uploads/2018/03/James-Van-Der-Beek-Dawson-Crying.jpg)

**Comment by AntonioCS** [comment]
@hanickadot I just downloaded the latest version https://github.com/hanickadot/compile-time-regular-expressions/blob/master/single-header/ctre.hpp

included it in my project and I get the same errors. I thought this was an issues with `vcpkg` not using the latest version. What am I doing wrong?

Here is a screenshot of the errors, they are the same but the line error number on the second is different as I am including the single header:

![image](https://user-images.githubusercontent.com/1086401/67743473-ab334800-fa16-11e9-8e17-cf8a0f78c482.png)

**Comment by hanickadot** [comment]
You need to provide minimal example, otherwise I'm unable to reproduce your error.

**Comment by hanickadot** [comment]
It will take a while, I don't have MSVC available and will be three weeks outside office.

**Comment by hanickadot** [comment]
Anyway I need you to provide the minimal example .cpp, preferably on compiler-explorer.com, as I'm unable to reprodece it.

**Comment by AntonioCS** [comment]
On compiler explorer all works well, but locally is where I get the error.
Not sure how I can provide an example as I got this just by including the header file.
I have removed all code related to CTRE, it's just the header.
As soon as I include the header and do ctrl+s, MSVC will show those errors in the Error List.
When I remove the header, the errors go away.

**Comment by hanickadot** [comment]
Also I need all compiler flags provided to cl.exe

**Comment by AntonioCS** [comment]
I am using cmake to produce everything, as soon as I get home I'll post it here.

**Comment by ray-haeb** [comment]
Does your project compile? These errors seem to be false positives from IntelliSense.

**Comment by AntonioCS** [comment]
Well... seems I have wasted everyone's time once again....
I was getting a compile issue but it cleared when I rebuilt everything. 
The CTRE errors are still there but I am able to compile.

I'll retry with vcpkg files.
