### ISSUE TITLE
(Idea) DSL for compatibility with older stds

### ISSUE THREAD

**Issue by DaMilyutin** [hanickadot/compile-time-regular-expressions#83]
There are some RE APIs possible:
* via string literals (as now) and fixed string under the hood
* via domain specific language.

I wonder if it is possible to divide your library into two parts.
One is for core RE-engine where you use finite automaton (I was on your talk in S.P.) 
and other is for API.

To my understanding API via string literals requires higher std.
But DSL can be done via older std.
Depending on your users I guess it is quite tricky.

That's up to you. Just shared the idea.

**Comment by hanickadot** [comment]
CTRE is able to work with C++17, lower standards are not supported. If you want to avoid parsing stage, you can:

```
auto matches = ctre::regular_expression<ctre::plus<ctre::char_range<'a', 'z'>>>().match(sv);
```

is equivalent to:

```
auto match = ctre::match<"[a-z]+">(sv);
```

**Comment by hanickadot** [comment]
And if you can't use C++20 for CNTTP syntax (`ctre::match<"pattern">(...)`) you can use C++17 approach:
```
static constexpr auto pattern = ctre::fixed_string("[a-z]+");

// later in code
auto match = ctre::match<pattern>(sv);
```
