### ISSUE TITLE
Certificate expired on referenced website

### ISSUE THREAD

**Issue by sthagen** [hanickadot/compile-time-regular-expressions#84]
Hi Hana,
just a small nit: people may have problems (like I had on ios) when visiting your https://compile-time.re/ website, because the certificate expired 2019-12-20. Maybe renew or if not possible, drop the `s` 😄 in the readme
Thank you for creating and sharing your compile time regex library and all the best,
Stefan

**Comment by hanickadot** [comment]
Fixed
