### ISSUE TITLE
Question: What is the `->` template operator?

### ISSUE THREAD

**Issue by mkitzan** [hanickadot/compile-time-regular-expressions#89]
Sorry to use the issues for asking a question. You use [this pattern](https://github.com/hanickadot/compile-time-regular-expressions/blob/master/single-header/ctre.hpp#L3783) a lot in your code to get things like `constexpr` objects as template arguments to work and such. I was just wondering what this is, so I can use it in my own compile time project. A link to some documentation about it/the actual name of it would be awesome!

**Comment by hanickadot** [comment]
https://en.cppreference.com/w/cpp/language/class_template_argument_deduction

**Comment by mkitzan** [comment]
Thank you!
