### ISSUE TITLE
Arbitrary binary data support

### ISSUE THREAD

**Issue by sykhro** [hanickadot/compile-time-regular-expressions#90]
My use-case is probably a little unusual: I need to scan for patterns of instructions in some binary files and extract addresses. ctre outperforms the current solution but unfortunately it fails to match anything that has data going above the ascii range:
```
static constexpr auto p1= ctll::fixed_string{"\x01\x02" "." "\xf3"};
static constexpr auto p2= ctll::fixed_string{"\x01\x02" "." "\x03"};
bool(ctre::match<p1>("\x01\x02\x03\xf3")); // false
bool(ctre::match<p2>("\x01\x02\x03\x03")); // true
```

**Comment by Alcaro** [comment]
Can confirm this bug exists.

[It also reproduces on UTF-8 input.](https://godbolt.org/z/H4PWRM)

Looks to me like a char / uint8_t mismatch somewhere.

**Comment by sykhro** [comment]
Found a workaround: escape the binary delimiter.
`"\x01\x02" "." "\xf3"` won't work, but ""\x01\x02" "." "\\xf3" does

**Comment by hanickadot** [comment]
In case you provides ordinary string literal or `u8""` string literal it's interpreted as UTF-8, if you provide `u""` literal it's interpreted as UTF-16 and if `U""` literal than as UTF-32.

Backslash and hexdec is a C++ language thing and it just sets a byte into the string. If you use double backslash to let the library interpret it, it will be inserted as a byte/value into the regex.

I will keep this issue open and will investigate if it will be easy to provide a "raw_fixed_string" for these usecases, but for now I'm not sure if it's the best course of action as you won't ever be able provide full 0-255 range of values as some `.` or `(` etc... have a meaning.

**Comment by hanickadot** [comment]
You can use raw string as pattern:
`ctre::match<R"(\x01\x02\x03)">(subject);`

**Comment by sykhro** [comment]
Doesn't work with clang unfortunately. Trunk says `error: reference to string literal is not allowed in a template argument`
while older versions say `error: non-type template argument does not refer to any declaration`. Can use fixed_string as a workaround

**Comment by hanickadot** [comment]
- clang will have CNTTP support (strings in template arguments) in 12.0
- you need to use C++17 syntax as in readme:

```
static constexpr ctll::fixed_string pattern = R"(\x01\x02\x03)";

bool match(const std::vector<uint8_t> & subject) {
 return ctre::match<pattern>(subject);
}
```
