### ISSUE TITLE
[Question] ctre::search

### ISSUE THREAD

**Issue by COM8** [hanickadot/compile-time-regular-expressions#92]
I'm trying to search and "consume" the match.
Example:
```c++
std::string in = "something AND nothing AND keyword OR foo";
std::string out = "";
auto m = ctre::search<"some regex">(in);
// Magic missing;
```
After this `in` should be `AND nothing AND keyword OR foo` and `out` should be `something`.
My regex matches `something` but how do I get the position of the first match in `in` so I can substring them?

**Comment by hanickadot** [comment]
```
std::cout << std::string_view{m.get<1>()} << "\n";
```
