### ISSUE TITLE
Support for \v and \h (horizontal and vertical space)

### ISSUE THREAD

**Issue by Andersama** [hanickadot/compile-time-regular-expressions#99]
PCRE syntax has both \v and \h defined as character classes, bit of a trip up to find \h and \v aren't supported.
\h should match spaces and tabs ' ' and '\t' (and unicode variations of those)
\v should match newlines, line feeds and carriage returns, \n \r \f (and unicode variations of those) (there is a paragraph and line separator in unicode which would fall into this category I think)

atoms_characters.hpp should also probably contain something like the following:
```c
namespace ctre {
    using hspace_chars = ctre::enumeration<' ', '\t'>; //etc
    using vspace_chars = ctre::enumeration<'\n','\r','\f','\v'>; //etc
};
```

**Comment by hanickadot** [comment]
Fixed in fd554853d5b1cf36d9a21c1b62cb2ec4922cbe68
